// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/database (interfaces: OutputService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOutputService is a mock of OutputService interface.
type MockOutputService struct {
	ctrl     *gomock.Controller
	recorder *MockOutputServiceMockRecorder
}

// MockOutputServiceMockRecorder is the mock recorder for MockOutputService.
type MockOutputServiceMockRecorder struct {
	mock *MockOutputService
}

// NewMockOutputService creates a new mock instance.
func NewMockOutputService(ctrl *gomock.Controller) *MockOutputService {
	mock := &MockOutputService{ctrl: ctrl}
	mock.recorder = &MockOutputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutputService) EXPECT() *MockOutputServiceMockRecorder {
	return m.recorder
}

// OutputRemoved mocks base method.
func (m *MockOutputService) OutputRemoved(arg0 string, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutputRemoved", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OutputRemoved indicates an expected call of OutputRemoved.
func (mr *MockOutputServiceMockRecorder) OutputRemoved(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutputRemoved", reflect.TypeOf((*MockOutputService)(nil).OutputRemoved), arg0, arg1)
}
