// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package messenger

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessenger creates a new instance of MockMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessenger {
	mock := &MockMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessenger is an autogenerated mock type for the Messenger type
type MockMessenger struct {
	mock.Mock
}

type MockMessenger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessenger) EXPECT() *MockMessenger_Expecter {
	return &MockMessenger_Expecter{mock: &_m.Mock}
}

// CreateChannel provides a mock function for the type MockMessenger
func (_mock *MockMessenger) CreateChannel(userID string) (*ChannelResponse, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 *ChannelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ChannelResponse, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ChannelResponse); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChannelResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessenger_CreateChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChannel'
type MockMessenger_CreateChannel_Call struct {
	*mock.Call
}

// CreateChannel is a helper method to define mock.On call
//   - userID string
func (_e *MockMessenger_Expecter) CreateChannel(userID interface{}) *MockMessenger_CreateChannel_Call {
	return &MockMessenger_CreateChannel_Call{Call: _e.mock.On("CreateChannel", userID)}
}

func (_c *MockMessenger_CreateChannel_Call) Run(run func(userID string)) *MockMessenger_CreateChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_CreateChannel_Call) Return(channelResponse *ChannelResponse, err error) *MockMessenger_CreateChannel_Call {
	_c.Call.Return(channelResponse, err)
	return _c
}

func (_c *MockMessenger_CreateChannel_Call) RunAndReturn(run func(userID string) (*ChannelResponse, error)) *MockMessenger_CreateChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessageAsync provides a mock function for the type MockMessenger
func (_mock *MockMessenger) DeleteMessageAsync(deleteAction *Delete) error {
	ret := _mock.Called(deleteAction)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessageAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Delete) error); ok {
		r0 = returnFunc(deleteAction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_DeleteMessageAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessageAsync'
type MockMessenger_DeleteMessageAsync_Call struct {
	*mock.Call
}

// DeleteMessageAsync is a helper method to define mock.On call
//   - deleteAction *Delete
func (_e *MockMessenger_Expecter) DeleteMessageAsync(deleteAction interface{}) *MockMessenger_DeleteMessageAsync_Call {
	return &MockMessenger_DeleteMessageAsync_Call{Call: _e.mock.On("DeleteMessageAsync", deleteAction)}
}

func (_c *MockMessenger_DeleteMessageAsync_Call) Run(run func(deleteAction *Delete)) *MockMessenger_DeleteMessageAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Delete
		if args[0] != nil {
			arg0 = args[0].(*Delete)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_DeleteMessageAsync_Call) Return(err error) *MockMessenger_DeleteMessageAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_DeleteMessageAsync_Call) RunAndReturn(run func(deleteAction *Delete) error) *MockMessenger_DeleteMessageAsync_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendMessage(message *Message) (*MessageResponse, error) {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *MessageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Message) (*MessageResponse, error)); ok {
		return returnFunc(message)
	}
	if returnFunc, ok := ret.Get(0).(func(*Message) *MessageResponse); ok {
		r0 = returnFunc(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Message) error); ok {
		r1 = returnFunc(message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessenger_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessenger_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - message *Message
func (_e *MockMessenger_Expecter) SendMessage(message interface{}) *MockMessenger_SendMessage_Call {
	return &MockMessenger_SendMessage_Call{Call: _e.mock.On("SendMessage", message)}
}

func (_c *MockMessenger_SendMessage_Call) Run(run func(message *Message)) *MockMessenger_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Message
		if args[0] != nil {
			arg0 = args[0].(*Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_SendMessage_Call) Return(messageResponse *MessageResponse, err error) *MockMessenger_SendMessage_Call {
	_c.Call.Return(messageResponse, err)
	return _c
}

func (_c *MockMessenger_SendMessage_Call) RunAndReturn(run func(message *Message) (*MessageResponse, error)) *MockMessenger_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageAsync provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendMessageAsync(message *Message) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Message) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_SendMessageAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageAsync'
type MockMessenger_SendMessageAsync_Call struct {
	*mock.Call
}

// SendMessageAsync is a helper method to define mock.On call
//   - message *Message
func (_e *MockMessenger_Expecter) SendMessageAsync(message interface{}) *MockMessenger_SendMessageAsync_Call {
	return &MockMessenger_SendMessageAsync_Call{Call: _e.mock.On("SendMessageAsync", message)}
}

func (_c *MockMessenger_SendMessageAsync_Call) Run(run func(message *Message)) *MockMessenger_SendMessageAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Message
		if args[0] != nil {
			arg0 = args[0].(*Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_SendMessageAsync_Call) Return(err error) *MockMessenger_SendMessageAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_SendMessageAsync_Call) RunAndReturn(run func(message *Message) error) *MockMessenger_SendMessageAsync_Call {
	_c.Call.Return(run)
	return _c
}

// SendReactionAsync provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendReactionAsync(reaction *Reaction) error {
	ret := _mock.Called(reaction)

	if len(ret) == 0 {
		panic("no return value specified for SendReactionAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Reaction) error); ok {
		r0 = returnFunc(reaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_SendReactionAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReactionAsync'
type MockMessenger_SendReactionAsync_Call struct {
	*mock.Call
}

// SendReactionAsync is a helper method to define mock.On call
//   - reaction *Reaction
func (_e *MockMessenger_Expecter) SendReactionAsync(reaction interface{}) *MockMessenger_SendReactionAsync_Call {
	return &MockMessenger_SendReactionAsync_Call{Call: _e.mock.On("SendReactionAsync", reaction)}
}

func (_c *MockMessenger_SendReactionAsync_Call) Run(run func(reaction *Reaction)) *MockMessenger_SendReactionAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Reaction
		if args[0] != nil {
			arg0 = args[0].(*Reaction)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_SendReactionAsync_Call) Return(err error) *MockMessenger_SendReactionAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_SendReactionAsync_Call) RunAndReturn(run func(reaction *Reaction) error) *MockMessenger_SendReactionAsync_Call {
	_c.Call.Return(run)
	return _c
}

// SendRedactAsync provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendRedactAsync(redact *Redact) error {
	ret := _mock.Called(redact)

	if len(ret) == 0 {
		panic("no return value specified for SendRedactAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Redact) error); ok {
		r0 = returnFunc(redact)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_SendRedactAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRedactAsync'
type MockMessenger_SendRedactAsync_Call struct {
	*mock.Call
}

// SendRedactAsync is a helper method to define mock.On call
//   - redact *Redact
func (_e *MockMessenger_Expecter) SendRedactAsync(redact interface{}) *MockMessenger_SendRedactAsync_Call {
	return &MockMessenger_SendRedactAsync_Call{Call: _e.mock.On("SendRedactAsync", redact)}
}

func (_c *MockMessenger_SendRedactAsync_Call) Run(run func(redact *Redact)) *MockMessenger_SendRedactAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Redact
		if args[0] != nil {
			arg0 = args[0].(*Redact)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_SendRedactAsync_Call) Return(err error) *MockMessenger_SendRedactAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_SendRedactAsync_Call) RunAndReturn(run func(redact *Redact) error) *MockMessenger_SendRedactAsync_Call {
	_c.Call.Return(run)
	return _c
}

// SendResponse provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendResponse(response *Response) (*MessageResponse, error) {
	ret := _mock.Called(response)

	if len(ret) == 0 {
		panic("no return value specified for SendResponse")
	}

	var r0 *MessageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Response) (*MessageResponse, error)); ok {
		return returnFunc(response)
	}
	if returnFunc, ok := ret.Get(0).(func(*Response) *MessageResponse); ok {
		r0 = returnFunc(response)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MessageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Response) error); ok {
		r1 = returnFunc(response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessenger_SendResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResponse'
type MockMessenger_SendResponse_Call struct {
	*mock.Call
}

// SendResponse is a helper method to define mock.On call
//   - response *Response
func (_e *MockMessenger_Expecter) SendResponse(response interface{}) *MockMessenger_SendResponse_Call {
	return &MockMessenger_SendResponse_Call{Call: _e.mock.On("SendResponse", response)}
}

func (_c *MockMessenger_SendResponse_Call) Run(run func(response *Response)) *MockMessenger_SendResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Response
		if args[0] != nil {
			arg0 = args[0].(*Response)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_SendResponse_Call) Return(messageResponse *MessageResponse, err error) *MockMessenger_SendResponse_Call {
	_c.Call.Return(messageResponse, err)
	return _c
}

func (_c *MockMessenger_SendResponse_Call) RunAndReturn(run func(response *Response) (*MessageResponse, error)) *MockMessenger_SendResponse_Call {
	_c.Call.Return(run)
	return _c
}

// SendResponseAsync provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendResponseAsync(response *Response) error {
	ret := _mock.Called(response)

	if len(ret) == 0 {
		panic("no return value specified for SendResponseAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Response) error); ok {
		r0 = returnFunc(response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_SendResponseAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResponseAsync'
type MockMessenger_SendResponseAsync_Call struct {
	*mock.Call
}

// SendResponseAsync is a helper method to define mock.On call
//   - response *Response
func (_e *MockMessenger_Expecter) SendResponseAsync(response interface{}) *MockMessenger_SendResponseAsync_Call {
	return &MockMessenger_SendResponseAsync_Call{Call: _e.mock.On("SendResponseAsync", response)}
}

func (_c *MockMessenger_SendResponseAsync_Call) Run(run func(response *Response)) *MockMessenger_SendResponseAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Response
		if args[0] != nil {
			arg0 = args[0].(*Response)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessenger_SendResponseAsync_Call) Return(err error) *MockMessenger_SendResponseAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_SendResponseAsync_Call) RunAndReturn(run func(response *Response) error) *MockMessenger_SendResponseAsync_Call {
	_c.Call.Return(run)
	return _c
}
