// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInputService creates a new instance of MockInputService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInputService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInputService {
	mock := &MockInputService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInputService is an autogenerated mock type for the InputService type
type MockInputService struct {
	mock.Mock
}

type MockInputService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInputService) EXPECT() *MockInputService_Expecter {
	return &MockInputService_Expecter{mock: &_m.Mock}
}

// InputRemoved provides a mock function for the type MockInputService
func (_mock *MockInputService) InputRemoved(inputType string, inputID uint) error {
	ret := _mock.Called(inputType, inputID)

	if len(ret) == 0 {
		panic("no return value specified for InputRemoved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = returnFunc(inputType, inputID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInputService_InputRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InputRemoved'
type MockInputService_InputRemoved_Call struct {
	*mock.Call
}

// InputRemoved is a helper method to define mock.On call
//   - inputType string
//   - inputID uint
func (_e *MockInputService_Expecter) InputRemoved(inputType interface{}, inputID interface{}) *MockInputService_InputRemoved_Call {
	return &MockInputService_InputRemoved_Call{Call: _e.mock.On("InputRemoved", inputType, inputID)}
}

func (_c *MockInputService_InputRemoved_Call) Run(run func(inputType string, inputID uint)) *MockInputService_InputRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInputService_InputRemoved_Call) Return(err error) *MockInputService_InputRemoved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInputService_InputRemoved_Call) RunAndReturn(run func(inputType string, inputID uint) error) *MockInputService_InputRemoved_Call {
	_c.Call.Return(run)
	return _c
}
