// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOutputService creates a new instance of MockOutputService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutputService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutputService {
	mock := &MockOutputService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutputService is an autogenerated mock type for the OutputService type
type MockOutputService struct {
	mock.Mock
}

type MockOutputService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutputService) EXPECT() *MockOutputService_Expecter {
	return &MockOutputService_Expecter{mock: &_m.Mock}
}

// OutputRemoved provides a mock function for the type MockOutputService
func (_mock *MockOutputService) OutputRemoved(outputType string, outputID uint) error {
	ret := _mock.Called(outputType, outputID)

	if len(ret) == 0 {
		panic("no return value specified for OutputRemoved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = returnFunc(outputType, outputID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutputService_OutputRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutputRemoved'
type MockOutputService_OutputRemoved_Call struct {
	*mock.Call
}

// OutputRemoved is a helper method to define mock.On call
//   - outputType string
//   - outputID uint
func (_e *MockOutputService_Expecter) OutputRemoved(outputType interface{}, outputID interface{}) *MockOutputService_OutputRemoved_Call {
	return &MockOutputService_OutputRemoved_Call{Call: _e.mock.On("OutputRemoved", outputType, outputID)}
}

func (_c *MockOutputService_OutputRemoved_Call) Run(run func(outputType string, outputID uint)) *MockOutputService_OutputRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutputService_OutputRemoved_Call) Return(err error) *MockOutputService_OutputRemoved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutputService_OutputRemoved_Call) RunAndReturn(run func(outputType string, outputID uint) error) *MockOutputService_OutputRemoved_Call {
	_c.Call.Return(run)
	return _c
}
