// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddInputToChannel provides a mock function for the type MockService
func (_mock *MockService) AddInputToChannel(v uint, input *Input) error {
	ret := _mock.Called(v, input)

	if len(ret) == 0 {
		panic("no return value specified for AddInputToChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, *Input) error); ok {
		r0 = returnFunc(v, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddInputToChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddInputToChannel'
type MockService_AddInputToChannel_Call struct {
	*mock.Call
}

// AddInputToChannel is a helper method to define mock.On call
//   - v uint
//   - input *Input
func (_e *MockService_Expecter) AddInputToChannel(v interface{}, input interface{}) *MockService_AddInputToChannel_Call {
	return &MockService_AddInputToChannel_Call{Call: _e.mock.On("AddInputToChannel", v, input)}
}

func (_c *MockService_AddInputToChannel_Call) Run(run func(v uint, input *Input)) *MockService_AddInputToChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *Input
		if args[1] != nil {
			arg1 = args[1].(*Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_AddInputToChannel_Call) Return(err error) *MockService_AddInputToChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddInputToChannel_Call) RunAndReturn(run func(v uint, input *Input) error) *MockService_AddInputToChannel_Call {
	_c.Call.Return(run)
	return _c
}

// AddOutputToChannel provides a mock function for the type MockService
func (_mock *MockService) AddOutputToChannel(v uint, output *Output) error {
	ret := _mock.Called(v, output)

	if len(ret) == 0 {
		panic("no return value specified for AddOutputToChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, *Output) error); ok {
		r0 = returnFunc(v, output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_AddOutputToChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOutputToChannel'
type MockService_AddOutputToChannel_Call struct {
	*mock.Call
}

// AddOutputToChannel is a helper method to define mock.On call
//   - v uint
//   - output *Output
func (_e *MockService_Expecter) AddOutputToChannel(v interface{}, output interface{}) *MockService_AddOutputToChannel_Call {
	return &MockService_AddOutputToChannel_Call{Call: _e.mock.On("AddOutputToChannel", v, output)}
}

func (_c *MockService_AddOutputToChannel_Call) Run(run func(v uint, output *Output)) *MockService_AddOutputToChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *Output
		if args[1] != nil {
			arg1 = args[1].(*Output)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_AddOutputToChannel_Call) Return(err error) *MockService_AddOutputToChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_AddOutputToChannel_Call) RunAndReturn(run func(v uint, output *Output) error) *MockService_AddOutputToChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function for the type MockService
func (_mock *MockService) Cleanup(opts *CleanupOpts) (int64, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*CleanupOpts) (int64, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(*CleanupOpts) int64); ok {
		r0 = returnFunc(opts)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*CleanupOpts) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockService_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - opts *CleanupOpts
func (_e *MockService_Expecter) Cleanup(opts interface{}) *MockService_Cleanup_Call {
	return &MockService_Cleanup_Call{Call: _e.mock.On("Cleanup", opts)}
}

func (_c *MockService_Cleanup_Call) Run(run func(opts *CleanupOpts)) *MockService_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *CleanupOpts
		if args[0] != nil {
			arg0 = args[0].(*CleanupOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Cleanup_Call) Return(n int64, err error) *MockService_Cleanup_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_Cleanup_Call) RunAndReturn(run func(opts *CleanupOpts) (int64, error)) *MockService_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChannel provides a mock function for the type MockService
func (_mock *MockService) DeleteChannel(channelID uint) error {
	ret := _mock.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(channelID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChannel'
type MockService_DeleteChannel_Call struct {
	*mock.Call
}

// DeleteChannel is a helper method to define mock.On call
//   - channelID uint
func (_e *MockService_Expecter) DeleteChannel(channelID interface{}) *MockService_DeleteChannel_Call {
	return &MockService_DeleteChannel_Call{Call: _e.mock.On("DeleteChannel", channelID)}
}

func (_c *MockService_DeleteChannel_Call) Run(run func(channelID uint)) *MockService_DeleteChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteChannel_Call) Return(err error) *MockService_DeleteChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteChannel_Call) RunAndReturn(run func(channelID uint) error) *MockService_DeleteChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function for the type MockService
func (_mock *MockService) DeleteEvent(event *Event) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Event) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockService_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - event *Event
func (_e *MockService_Expecter) DeleteEvent(event interface{}) *MockService_DeleteEvent_Call {
	return &MockService_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", event)}
}

func (_c *MockService_DeleteEvent_Call) Run(run func(event *Event)) *MockService_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Event
		if args[0] != nil {
			arg0 = args[0].(*Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteEvent_Call) Return(err error) *MockService_DeleteEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteEvent_Call) RunAndReturn(run func(event *Event) error) *MockService_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannelByID provides a mock function for the type MockService
func (_mock *MockService) GetChannelByID(v uint) (*Channel, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelByID")
	}

	var r0 *Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Channel, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Channel); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetChannelByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelByID'
type MockService_GetChannelByID_Call struct {
	*mock.Call
}

// GetChannelByID is a helper method to define mock.On call
//   - v uint
func (_e *MockService_Expecter) GetChannelByID(v interface{}) *MockService_GetChannelByID_Call {
	return &MockService_GetChannelByID_Call{Call: _e.mock.On("GetChannelByID", v)}
}

func (_c *MockService_GetChannelByID_Call) Run(run func(v uint)) *MockService_GetChannelByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetChannelByID_Call) Return(channel *Channel, err error) *MockService_GetChannelByID_Call {
	_c.Call.Return(channel, err)
	return _c
}

func (_c *MockService_GetChannelByID_Call) RunAndReturn(run func(v uint) (*Channel, error)) *MockService_GetChannelByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannels provides a mock function for the type MockService
func (_mock *MockService) GetChannels() ([]Channel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChannels")
	}

	var r0 []Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Channel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Channel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannels'
type MockService_GetChannels_Call struct {
	*mock.Call
}

// GetChannels is a helper method to define mock.On call
func (_e *MockService_Expecter) GetChannels() *MockService_GetChannels_Call {
	return &MockService_GetChannels_Call{Call: _e.mock.On("GetChannels")}
}

func (_c *MockService_GetChannels_Call) Run(run func()) *MockService_GetChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetChannels_Call) Return(channels []Channel, err error) *MockService_GetChannels_Call {
	_c.Call.Return(channels, err)
	return _c
}

func (_c *MockService_GetChannels_Call) RunAndReturn(run func() ([]Channel, error)) *MockService_GetChannels_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsByChannel provides a mock function for the type MockService
func (_mock *MockService) GetEventsByChannel(v uint) ([]Event, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByChannel")
	}

	var r0 []Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]Event, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []Event); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetEventsByChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsByChannel'
type MockService_GetEventsByChannel_Call struct {
	*mock.Call
}

// GetEventsByChannel is a helper method to define mock.On call
//   - v uint
func (_e *MockService_Expecter) GetEventsByChannel(v interface{}) *MockService_GetEventsByChannel_Call {
	return &MockService_GetEventsByChannel_Call{Call: _e.mock.On("GetEventsByChannel", v)}
}

func (_c *MockService_GetEventsByChannel_Call) Run(run func(v uint)) *MockService_GetEventsByChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetEventsByChannel_Call) Return(events []Event, err error) *MockService_GetEventsByChannel_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockService_GetEventsByChannel_Call) RunAndReturn(run func(v uint) ([]Event, error)) *MockService_GetEventsByChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsPending provides a mock function for the type MockService
func (_mock *MockService) GetEventsPending() ([]Event, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventsPending")
	}

	var r0 []Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]Event, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []Event); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetEventsPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsPending'
type MockService_GetEventsPending_Call struct {
	*mock.Call
}

// GetEventsPending is a helper method to define mock.On call
func (_e *MockService_Expecter) GetEventsPending() *MockService_GetEventsPending_Call {
	return &MockService_GetEventsPending_Call{Call: _e.mock.On("GetEventsPending")}
}

func (_c *MockService_GetEventsPending_Call) Run(run func()) *MockService_GetEventsPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetEventsPending_Call) Return(events []Event, err error) *MockService_GetEventsPending_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockService_GetEventsPending_Call) RunAndReturn(run func() ([]Event, error)) *MockService_GetEventsPending_Call {
	_c.Call.Return(run)
	return _c
}

// GetInputByID provides a mock function for the type MockService
func (_mock *MockService) GetInputByID(v uint) (*Input, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for GetInputByID")
	}

	var r0 *Input
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Input, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Input); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Input)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetInputByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInputByID'
type MockService_GetInputByID_Call struct {
	*mock.Call
}

// GetInputByID is a helper method to define mock.On call
//   - v uint
func (_e *MockService_Expecter) GetInputByID(v interface{}) *MockService_GetInputByID_Call {
	return &MockService_GetInputByID_Call{Call: _e.mock.On("GetInputByID", v)}
}

func (_c *MockService_GetInputByID_Call) Run(run func(v uint)) *MockService_GetInputByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetInputByID_Call) Return(input *Input, err error) *MockService_GetInputByID_Call {
	_c.Call.Return(input, err)
	return _c
}

func (_c *MockService_GetInputByID_Call) RunAndReturn(run func(v uint) (*Input, error)) *MockService_GetInputByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInputByType provides a mock function for the type MockService
func (_mock *MockService) GetInputByType(inputID uint, inputType string) (*Input, error) {
	ret := _mock.Called(inputID, inputType)

	if len(ret) == 0 {
		panic("no return value specified for GetInputByType")
	}

	var r0 *Input
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) (*Input, error)); ok {
		return returnFunc(inputID, inputType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, string) *Input); ok {
		r0 = returnFunc(inputID, inputType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Input)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = returnFunc(inputID, inputType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetInputByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInputByType'
type MockService_GetInputByType_Call struct {
	*mock.Call
}

// GetInputByType is a helper method to define mock.On call
//   - inputID uint
//   - inputType string
func (_e *MockService_Expecter) GetInputByType(inputID interface{}, inputType interface{}) *MockService_GetInputByType_Call {
	return &MockService_GetInputByType_Call{Call: _e.mock.On("GetInputByType", inputID, inputType)}
}

func (_c *MockService_GetInputByType_Call) Run(run func(inputID uint, inputType string)) *MockService_GetInputByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetInputByType_Call) Return(input *Input, err error) *MockService_GetInputByType_Call {
	_c.Call.Return(input, err)
	return _c
}

func (_c *MockService_GetInputByType_Call) RunAndReturn(run func(inputID uint, inputType string) (*Input, error)) *MockService_GetInputByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetOutputByID provides a mock function for the type MockService
func (_mock *MockService) GetOutputByID(v uint) (*Output, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for GetOutputByID")
	}

	var r0 *Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*Output, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *Output); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOutputByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutputByID'
type MockService_GetOutputByID_Call struct {
	*mock.Call
}

// GetOutputByID is a helper method to define mock.On call
//   - v uint
func (_e *MockService_Expecter) GetOutputByID(v interface{}) *MockService_GetOutputByID_Call {
	return &MockService_GetOutputByID_Call{Call: _e.mock.On("GetOutputByID", v)}
}

func (_c *MockService_GetOutputByID_Call) Run(run func(v uint)) *MockService_GetOutputByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetOutputByID_Call) Return(output *Output, err error) *MockService_GetOutputByID_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockService_GetOutputByID_Call) RunAndReturn(run func(v uint) (*Output, error)) *MockService_GetOutputByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOutputByType provides a mock function for the type MockService
func (_mock *MockService) GetOutputByType(outputID uint, outputType string) (*Output, error) {
	ret := _mock.Called(outputID, outputType)

	if len(ret) == 0 {
		panic("no return value specified for GetOutputByType")
	}

	var r0 *Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, string) (*Output, error)); ok {
		return returnFunc(outputID, outputType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, string) *Output); ok {
		r0 = returnFunc(outputID, outputType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = returnFunc(outputID, outputType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOutputByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutputByType'
type MockService_GetOutputByType_Call struct {
	*mock.Call
}

// GetOutputByType is a helper method to define mock.On call
//   - outputID uint
//   - outputType string
func (_e *MockService_Expecter) GetOutputByType(outputID interface{}, outputType interface{}) *MockService_GetOutputByType_Call {
	return &MockService_GetOutputByType_Call{Call: _e.mock.On("GetOutputByType", outputID, outputType)}
}

func (_c *MockService_GetOutputByType_Call) Run(run func(outputID uint, outputType string)) *MockService_GetOutputByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOutputByType_Call) Return(output *Output, err error) *MockService_GetOutputByType_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockService_GetOutputByType_Call) RunAndReturn(run func(outputID uint, outputType string) (*Output, error)) *MockService_GetOutputByType_Call {
	_c.Call.Return(run)
	return _c
}

// GormDB provides a mock function for the type MockService
func (_mock *MockService) GormDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GormDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockService_GormDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GormDB'
type MockService_GormDB_Call struct {
	*mock.Call
}

// GormDB is a helper method to define mock.On call
func (_e *MockService_Expecter) GormDB() *MockService_GormDB_Call {
	return &MockService_GormDB_Call{Call: _e.mock.On("GormDB")}
}

func (_c *MockService_GormDB_Call) Run(run func()) *MockService_GormDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GormDB_Call) Return(dB *gorm.DB) *MockService_GormDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockService_GormDB_Call) RunAndReturn(run func() *gorm.DB) *MockService_GormDB_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function for the type MockService
func (_mock *MockService) ListEvents(opts *ListEventsOpts) ([]Event, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ListEventsOpts) ([]Event, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(*ListEventsOpts) []Event); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ListEventsOpts) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type MockService_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - opts *ListEventsOpts
func (_e *MockService_Expecter) ListEvents(opts interface{}) *MockService_ListEvents_Call {
	return &MockService_ListEvents_Call{Call: _e.mock.On("ListEvents", opts)}
}

func (_c *MockService_ListEvents_Call) Run(run func(opts *ListEventsOpts)) *MockService_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ListEventsOpts
		if args[0] != nil {
			arg0 = args[0].(*ListEventsOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListEvents_Call) Return(events []Event, err error) *MockService_ListEvents_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockService_ListEvents_Call) RunAndReturn(run func(opts *ListEventsOpts) ([]Event, error)) *MockService_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannel provides a mock function for the type MockService
func (_mock *MockService) NewChannel(channel *Channel) (*Channel, error) {
	ret := _mock.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for NewChannel")
	}

	var r0 *Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Channel) (*Channel, error)); ok {
		return returnFunc(channel)
	}
	if returnFunc, ok := ret.Get(0).(func(*Channel) *Channel); ok {
		r0 = returnFunc(channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Channel) error); ok {
		r1 = returnFunc(channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewChannel'
type MockService_NewChannel_Call struct {
	*mock.Call
}

// NewChannel is a helper method to define mock.On call
//   - channel *Channel
func (_e *MockService_Expecter) NewChannel(channel interface{}) *MockService_NewChannel_Call {
	return &MockService_NewChannel_Call{Call: _e.mock.On("NewChannel", channel)}
}

func (_c *MockService_NewChannel_Call) Run(run func(channel *Channel)) *MockService_NewChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Channel
		if args[0] != nil {
			arg0 = args[0].(*Channel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewChannel_Call) Return(channel1 *Channel, err error) *MockService_NewChannel_Call {
	_c.Call.Return(channel1, err)
	return _c
}

func (_c *MockService_NewChannel_Call) RunAndReturn(run func(channel *Channel) (*Channel, error)) *MockService_NewChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewEvent provides a mock function for the type MockService
func (_mock *MockService) NewEvent(event *Event) (*Event, error) {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for NewEvent")
	}

	var r0 *Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Event) (*Event, error)); ok {
		return returnFunc(event)
	}
	if returnFunc, ok := ret.Get(0).(func(*Event) *Event); ok {
		r0 = returnFunc(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Event) error); ok {
		r1 = returnFunc(event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewEvent'
type MockService_NewEvent_Call struct {
	*mock.Call
}

// NewEvent is a helper method to define mock.On call
//   - event *Event
func (_e *MockService_Expecter) NewEvent(event interface{}) *MockService_NewEvent_Call {
	return &MockService_NewEvent_Call{Call: _e.mock.On("NewEvent", event)}
}

func (_c *MockService_NewEvent_Call) Run(run func(event *Event)) *MockService_NewEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Event
		if args[0] != nil {
			arg0 = args[0].(*Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewEvent_Call) Return(event1 *Event, err error) *MockService_NewEvent_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockService_NewEvent_Call) RunAndReturn(run func(event *Event) (*Event, error)) *MockService_NewEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewEvents provides a mock function for the type MockService
func (_mock *MockService) NewEvents(events []Event) error {
	ret := _mock.Called(events)

	if len(ret) == 0 {
		panic("no return value specified for NewEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]Event) error); ok {
		r0 = returnFunc(events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_NewEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewEvents'
type MockService_NewEvents_Call struct {
	*mock.Call
}

// NewEvents is a helper method to define mock.On call
//   - events []Event
func (_e *MockService_Expecter) NewEvents(events interface{}) *MockService_NewEvents_Call {
	return &MockService_NewEvents_Call{Call: _e.mock.On("NewEvents", events)}
}

func (_c *MockService_NewEvents_Call) Run(run func(events []Event)) *MockService_NewEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []Event
		if args[0] != nil {
			arg0 = args[0].([]Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewEvents_Call) Return(err error) *MockService_NewEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_NewEvents_Call) RunAndReturn(run func(events []Event) error) *MockService_NewEvents_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveInputFromChannel provides a mock function for the type MockService
func (_mock *MockService) RemoveInputFromChannel(channelID uint, inputID uint) error {
	ret := _mock.Called(channelID, inputID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveInputFromChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = returnFunc(channelID, inputID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveInputFromChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveInputFromChannel'
type MockService_RemoveInputFromChannel_Call struct {
	*mock.Call
}

// RemoveInputFromChannel is a helper method to define mock.On call
//   - channelID uint
//   - inputID uint
func (_e *MockService_Expecter) RemoveInputFromChannel(channelID interface{}, inputID interface{}) *MockService_RemoveInputFromChannel_Call {
	return &MockService_RemoveInputFromChannel_Call{Call: _e.mock.On("RemoveInputFromChannel", channelID, inputID)}
}

func (_c *MockService_RemoveInputFromChannel_Call) Run(run func(channelID uint, inputID uint)) *MockService_RemoveInputFromChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RemoveInputFromChannel_Call) Return(err error) *MockService_RemoveInputFromChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveInputFromChannel_Call) RunAndReturn(run func(channelID uint, inputID uint) error) *MockService_RemoveInputFromChannel_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveOutputFromChannel provides a mock function for the type MockService
func (_mock *MockService) RemoveOutputFromChannel(channelID uint, outputID uint) error {
	ret := _mock.Called(channelID, outputID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveOutputFromChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = returnFunc(channelID, outputID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveOutputFromChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveOutputFromChannel'
type MockService_RemoveOutputFromChannel_Call struct {
	*mock.Call
}

// RemoveOutputFromChannel is a helper method to define mock.On call
//   - channelID uint
//   - outputID uint
func (_e *MockService_Expecter) RemoveOutputFromChannel(channelID interface{}, outputID interface{}) *MockService_RemoveOutputFromChannel_Call {
	return &MockService_RemoveOutputFromChannel_Call{Call: _e.mock.On("RemoveOutputFromChannel", channelID, outputID)}
}

func (_c *MockService_RemoveOutputFromChannel_Call) Run(run func(channelID uint, outputID uint)) *MockService_RemoveOutputFromChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RemoveOutputFromChannel_Call) Return(err error) *MockService_RemoveOutputFromChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveOutputFromChannel_Call) RunAndReturn(run func(channelID uint, outputID uint) error) *MockService_RemoveOutputFromChannel_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateChannel provides a mock function for the type MockService
func (_mock *MockService) UpdateChannel(channel *Channel) (*Channel, error) {
	ret := _mock.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChannel")
	}

	var r0 *Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Channel) (*Channel, error)); ok {
		return returnFunc(channel)
	}
	if returnFunc, ok := ret.Get(0).(func(*Channel) *Channel); ok {
		r0 = returnFunc(channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Channel) error); ok {
		r1 = returnFunc(channel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateChannel'
type MockService_UpdateChannel_Call struct {
	*mock.Call
}

// UpdateChannel is a helper method to define mock.On call
//   - channel *Channel
func (_e *MockService_Expecter) UpdateChannel(channel interface{}) *MockService_UpdateChannel_Call {
	return &MockService_UpdateChannel_Call{Call: _e.mock.On("UpdateChannel", channel)}
}

func (_c *MockService_UpdateChannel_Call) Run(run func(channel *Channel)) *MockService_UpdateChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Channel
		if args[0] != nil {
			arg0 = args[0].(*Channel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_UpdateChannel_Call) Return(channel1 *Channel, err error) *MockService_UpdateChannel_Call {
	_c.Call.Return(channel1, err)
	return _c
}

func (_c *MockService_UpdateChannel_Call) RunAndReturn(run func(channel *Channel) (*Channel, error)) *MockService_UpdateChannel_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function for the type MockService
func (_mock *MockService) UpdateEvent(event *Event) (*Event, error) {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 *Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Event) (*Event, error)); ok {
		return returnFunc(event)
	}
	if returnFunc, ok := ret.Get(0).(func(*Event) *Event); ok {
		r0 = returnFunc(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Event) error); ok {
		r1 = returnFunc(event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockService_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - event *Event
func (_e *MockService_Expecter) UpdateEvent(event interface{}) *MockService_UpdateEvent_Call {
	return &MockService_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", event)}
}

func (_c *MockService_UpdateEvent_Call) Run(run func(event *Event)) *MockService_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Event
		if args[0] != nil {
			arg0 = args[0].(*Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_UpdateEvent_Call) Return(event1 *Event, err error) *MockService_UpdateEvent_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *MockService_UpdateEvent_Call) RunAndReturn(run func(event *Event) (*Event, error)) *MockService_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOutput provides a mock function for the type MockService
func (_mock *MockService) UpdateOutput(output *Output) (*Output, error) {
	ret := _mock.Called(output)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOutput")
	}

	var r0 *Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Output) (*Output, error)); ok {
		return returnFunc(output)
	}
	if returnFunc, ok := ret.Get(0).(func(*Output) *Output); ok {
		r0 = returnFunc(output)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Output) error); ok {
		r1 = returnFunc(output)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOutput'
type MockService_UpdateOutput_Call struct {
	*mock.Call
}

// UpdateOutput is a helper method to define mock.On call
//   - output *Output
func (_e *MockService_Expecter) UpdateOutput(output interface{}) *MockService_UpdateOutput_Call {
	return &MockService_UpdateOutput_Call{Call: _e.mock.On("UpdateOutput", output)}
}

func (_c *MockService_UpdateOutput_Call) Run(run func(output *Output)) *MockService_UpdateOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Output
		if args[0] != nil {
			arg0 = args[0].(*Output)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_UpdateOutput_Call) Return(output1 *Output, err error) *MockService_UpdateOutput_Call {
	_c.Call.Return(output1, err)
	return _c
}

func (_c *MockService_UpdateOutput_Call) RunAndReturn(run func(output *Output) (*Output, error)) *MockService_UpdateOutput_Call {
	_c.Call.Return(run)
	return _c
}
