version: "2"
linters:
  default: all
  disable:
    - durationcheck
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - godot
    - godox
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - misspell
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - noinlineerr
    - funcorder
    - prealloc
  settings:
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/tj/assert
              desc: github.com/stretchr/testify/assert is preferred
    funlen:
      lines: 150
      statements: 80
    gocognit:
      min-complexity: 40
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
          - forcetypeassert
          - funlen
          - goconst
          - noctx
        path: (.*)_test\.go
      - linters:
          - forbidigo
        path: internal/connectors/matrix/tests
      - path: (.*)\/string\.go
        text: 'G404: Use of weak random number generator'
      - path: (.*)\/motivational_sentence\.go
        text: 'G404: Use of weak random number generator'
      - path: (.*)\/initializers\.go
        text: 'SA4009: argument db is overwritten before first use'
      - path: (.*).go
        text: 'G115: integer overflow conversion'
      - path: (.+)\.go$
        text: string `11:45 12\.11\.2014 \(UTC\)` has 3 occurrences, make it a constant
      - path: (.+)\.go$
        text: '`\(\*Syncer\)\.sendAndStoreReply` - `reminderID` always receives `0'
      - linters:
          - revive
        text: '^var-naming:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
