# Enabel debug mode for verbose logging
debug: false

# Database settings
database:
  # MySQL connection string
  # https://github.com/go-sql-driver/mysql#dsn-data-source-name
  connection: "root:mypass@tcp(localhost:3306)/remindme"
  # Log SQL statements, default disabled
  logstatements: false

# Daemon settings
daemon:
  # Intervals in which to run specific operations
  intervals:
    # Check for events, in seconds
    events: 30
    # Check for daily reminders, in seconds
    dailyreminders: 600