# Enable debug mode for verbose logging
debug: false

# Settings for the bots matrix account
matrixbotaccount:
  # Matrix user name
  username: "iamabot"
  # Matrix password
  password: fsddf
  # Matrix homeserver
  homeserver: fsdf
  # Device ID for the bot, used to identify the server connection
  deviceid: "my-bot-12345"
  
  ## EXPERIMENTAL ##
  # Set to true to allow end to end encryption
  e2ee: false
  # Device key for encryption
  devicekey: "dlfjgaöldf"

# Matrix username to interact with
# they will all be granted admin permissions
matrixusers: 
  - "yourmatrixuser"
  - "anotheruser"

# Settings regarding the bot
botsettings:
  # Allow users to invite the bot
  allowinvites: false
  # Maximum parallel users that the bot will accept. -1 to have no limit.
  # With to many users the bot might run into API rate limits of the matrix instance.
  maxuser: 10
  # Set to true to let the bot send reactions
  # enabling this will drastically increase send events, for heavy use you might run into rate limits of the bots instance
  sendreactions: false
  # Allow users (only admin users) to import reminders from an Ical link
  allowicalimport: false

# Database settings
database:
  # MySQL connection string
  # https://github.com/go-sql-driver/mysql#dsn-data-source-name
  connection: "username:password@protocol(address)/dbname"

# Webserver settings
webserver:
  # Set to true to enable the API. All further settings are only needed if the webserver is enabled.
  enabled: false 
  # Apikey to authenticate against the API. At least 20 characters.
  apikey: "1234"
  # The base url where the bot is reachable from outside
  baseurl: "my-bot.tld"