# Enable debug mode for verbose logging
debug: false

# Settings for the bots matrix account
matrixbotaccount:
  # Matrix user name
  username: "iamabot"
  # Matrix password
  password: fsddf
  # Matrix homeserver
  homeserver: fsdf

# Matrix username to interact with
matrixusers: 
  - "yourmatrixuser"
  - "anotheruser"

  # Database settings
database:
  # MySQL connection string
  # https://github.com/go-sql-driver/mysql#dsn-data-source-name
  connection: "username:password@protocol(address)/dbname"

# Webserver settings
webserver:
  # Set to true to enable the API
  enabled: false 
  # Apikey to authenticate against the API. At least 20 characters.
  apikey: "1234"