// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AddUserToRoom provides a mock function for the type MockService
func (_mock *MockService) AddUserToRoom(userID string, room *MatrixRoom) (*MatrixRoom, error) {
	ret := _mock.Called(userID, room)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToRoom")
	}

	var r0 *MatrixRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *MatrixRoom) (*MatrixRoom, error)); ok {
		return returnFunc(userID, room)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *MatrixRoom) *MatrixRoom); ok {
		r0 = returnFunc(userID, room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *MatrixRoom) error); ok {
		r1 = returnFunc(userID, room)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_AddUserToRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToRoom'
type MockService_AddUserToRoom_Call struct {
	*mock.Call
}

// AddUserToRoom is a helper method to define mock.On call
//   - userID string
//   - room *MatrixRoom
func (_e *MockService_Expecter) AddUserToRoom(userID interface{}, room interface{}) *MockService_AddUserToRoom_Call {
	return &MockService_AddUserToRoom_Call{Call: _e.mock.On("AddUserToRoom", userID, room)}
}

func (_c *MockService_AddUserToRoom_Call) Run(run func(userID string, room *MatrixRoom)) *MockService_AddUserToRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *MatrixRoom
		if args[1] != nil {
			arg1 = args[1].(*MatrixRoom)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_AddUserToRoom_Call) Return(matrixRoom *MatrixRoom, err error) *MockService_AddUserToRoom_Call {
	_c.Call.Return(matrixRoom, err)
	return _c
}

func (_c *MockService_AddUserToRoom_Call) RunAndReturn(run func(userID string, room *MatrixRoom) (*MatrixRoom, error)) *MockService_AddUserToRoom_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function for the type MockService
func (_mock *MockService) Cleanup() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockService_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockService_Expecter) Cleanup() *MockService_Cleanup_Call {
	return &MockService_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockService_Cleanup_Call) Run(run func()) *MockService_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Cleanup_Call) Return(err error) *MockService_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Cleanup_Call) RunAndReturn(run func() error) *MockService_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllEventsFromRoom provides a mock function for the type MockService
func (_mock *MockService) DeleteAllEventsFromRoom(roomID uint) error {
	ret := _mock.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllEventsFromRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteAllEventsFromRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllEventsFromRoom'
type MockService_DeleteAllEventsFromRoom_Call struct {
	*mock.Call
}

// DeleteAllEventsFromRoom is a helper method to define mock.On call
//   - roomID uint
func (_e *MockService_Expecter) DeleteAllEventsFromRoom(roomID interface{}) *MockService_DeleteAllEventsFromRoom_Call {
	return &MockService_DeleteAllEventsFromRoom_Call{Call: _e.mock.On("DeleteAllEventsFromRoom", roomID)}
}

func (_c *MockService_DeleteAllEventsFromRoom_Call) Run(run func(roomID uint)) *MockService_DeleteAllEventsFromRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteAllEventsFromRoom_Call) Return(err error) *MockService_DeleteAllEventsFromRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteAllEventsFromRoom_Call) RunAndReturn(run func(roomID uint) error) *MockService_DeleteAllEventsFromRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllMessagesFromRoom provides a mock function for the type MockService
func (_mock *MockService) DeleteAllMessagesFromRoom(roomID uint) error {
	ret := _mock.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllMessagesFromRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteAllMessagesFromRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllMessagesFromRoom'
type MockService_DeleteAllMessagesFromRoom_Call struct {
	*mock.Call
}

// DeleteAllMessagesFromRoom is a helper method to define mock.On call
//   - roomID uint
func (_e *MockService_Expecter) DeleteAllMessagesFromRoom(roomID interface{}) *MockService_DeleteAllMessagesFromRoom_Call {
	return &MockService_DeleteAllMessagesFromRoom_Call{Call: _e.mock.On("DeleteAllMessagesFromRoom", roomID)}
}

func (_c *MockService_DeleteAllMessagesFromRoom_Call) Run(run func(roomID uint)) *MockService_DeleteAllMessagesFromRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteAllMessagesFromRoom_Call) Return(err error) *MockService_DeleteAllMessagesFromRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteAllMessagesFromRoom_Call) RunAndReturn(run func(roomID uint) error) *MockService_DeleteAllMessagesFromRoom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoom provides a mock function for the type MockService
func (_mock *MockService) DeleteRoom(roomID uint) error {
	ret := _mock.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoom'
type MockService_DeleteRoom_Call struct {
	*mock.Call
}

// DeleteRoom is a helper method to define mock.On call
//   - roomID uint
func (_e *MockService_Expecter) DeleteRoom(roomID interface{}) *MockService_DeleteRoom_Call {
	return &MockService_DeleteRoom_Call{Call: _e.mock.On("DeleteRoom", roomID)}
}

func (_c *MockService_DeleteRoom_Call) Run(run func(roomID uint)) *MockService_DeleteRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteRoom_Call) Return(err error) *MockService_DeleteRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteRoom_Call) RunAndReturn(run func(roomID uint) error) *MockService_DeleteRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventByID provides a mock function for the type MockService
func (_mock *MockService) GetEventByID(eventID string) (*MatrixEvent, error) {
	ret := _mock.Called(eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByID")
	}

	var r0 *MatrixEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*MatrixEvent, error)); ok {
		return returnFunc(eventID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *MatrixEvent); ok {
		r0 = returnFunc(eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(eventID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetEventByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventByID'
type MockService_GetEventByID_Call struct {
	*mock.Call
}

// GetEventByID is a helper method to define mock.On call
//   - eventID string
func (_e *MockService_Expecter) GetEventByID(eventID interface{}) *MockService_GetEventByID_Call {
	return &MockService_GetEventByID_Call{Call: _e.mock.On("GetEventByID", eventID)}
}

func (_c *MockService_GetEventByID_Call) Run(run func(eventID string)) *MockService_GetEventByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetEventByID_Call) Return(matrixEvent *MatrixEvent, err error) *MockService_GetEventByID_Call {
	_c.Call.Return(matrixEvent, err)
	return _c
}

func (_c *MockService_GetEventByID_Call) RunAndReturn(run func(eventID string) (*MatrixEvent, error)) *MockService_GetEventByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventMessageByOutputAndEvent provides a mock function for the type MockService
func (_mock *MockService) GetEventMessageByOutputAndEvent(eventID uint, outputID uint, outputType string) (*MatrixMessage, error) {
	ret := _mock.Called(eventID, outputID, outputType)

	if len(ret) == 0 {
		panic("no return value specified for GetEventMessageByOutputAndEvent")
	}

	var r0 *MatrixMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint, string) (*MatrixMessage, error)); ok {
		return returnFunc(eventID, outputID, outputType)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint, string) *MatrixMessage); ok {
		r0 = returnFunc(eventID, outputID, outputType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint, string) error); ok {
		r1 = returnFunc(eventID, outputID, outputType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetEventMessageByOutputAndEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventMessageByOutputAndEvent'
type MockService_GetEventMessageByOutputAndEvent_Call struct {
	*mock.Call
}

// GetEventMessageByOutputAndEvent is a helper method to define mock.On call
//   - eventID uint
//   - outputID uint
//   - outputType string
func (_e *MockService_Expecter) GetEventMessageByOutputAndEvent(eventID interface{}, outputID interface{}, outputType interface{}) *MockService_GetEventMessageByOutputAndEvent_Call {
	return &MockService_GetEventMessageByOutputAndEvent_Call{Call: _e.mock.On("GetEventMessageByOutputAndEvent", eventID, outputID, outputType)}
}

func (_c *MockService_GetEventMessageByOutputAndEvent_Call) Run(run func(eventID uint, outputID uint, outputType string)) *MockService_GetEventMessageByOutputAndEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetEventMessageByOutputAndEvent_Call) Return(matrixMessage *MatrixMessage, err error) *MockService_GetEventMessageByOutputAndEvent_Call {
	_c.Call.Return(matrixMessage, err)
	return _c
}

func (_c *MockService_GetEventMessageByOutputAndEvent_Call) RunAndReturn(run func(eventID uint, outputID uint, outputType string) (*MatrixMessage, error)) *MockService_GetEventMessageByOutputAndEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastEvent provides a mock function for the type MockService
func (_mock *MockService) GetLastEvent() (*MatrixEvent, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastEvent")
	}

	var r0 *MatrixEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*MatrixEvent, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *MatrixEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetLastEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastEvent'
type MockService_GetLastEvent_Call struct {
	*mock.Call
}

// GetLastEvent is a helper method to define mock.On call
func (_e *MockService_Expecter) GetLastEvent() *MockService_GetLastEvent_Call {
	return &MockService_GetLastEvent_Call{Call: _e.mock.On("GetLastEvent")}
}

func (_c *MockService_GetLastEvent_Call) Run(run func()) *MockService_GetLastEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetLastEvent_Call) Return(matrixEvent *MatrixEvent, err error) *MockService_GetLastEvent_Call {
	_c.Call.Return(matrixEvent, err)
	return _c
}

func (_c *MockService_GetLastEvent_Call) RunAndReturn(run func() (*MatrixEvent, error)) *MockService_GetLastEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastMessage provides a mock function for the type MockService
func (_mock *MockService) GetLastMessage() (*MatrixMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastMessage")
	}

	var r0 *MatrixMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*MatrixMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *MatrixMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetLastMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastMessage'
type MockService_GetLastMessage_Call struct {
	*mock.Call
}

// GetLastMessage is a helper method to define mock.On call
func (_e *MockService_Expecter) GetLastMessage() *MockService_GetLastMessage_Call {
	return &MockService_GetLastMessage_Call{Call: _e.mock.On("GetLastMessage")}
}

func (_c *MockService_GetLastMessage_Call) Run(run func()) *MockService_GetLastMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetLastMessage_Call) Return(matrixMessage *MatrixMessage, err error) *MockService_GetLastMessage_Call {
	_c.Call.Return(matrixMessage, err)
	return _c
}

func (_c *MockService_GetLastMessage_Call) RunAndReturn(run func() (*MatrixMessage, error)) *MockService_GetLastMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageByID provides a mock function for the type MockService
func (_mock *MockService) GetMessageByID(messageID string) (*MatrixMessage, error) {
	ret := _mock.Called(messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByID")
	}

	var r0 *MatrixMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*MatrixMessage, error)); ok {
		return returnFunc(messageID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *MatrixMessage); ok {
		r0 = returnFunc(messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(messageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMessageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageByID'
type MockService_GetMessageByID_Call struct {
	*mock.Call
}

// GetMessageByID is a helper method to define mock.On call
//   - messageID string
func (_e *MockService_Expecter) GetMessageByID(messageID interface{}) *MockService_GetMessageByID_Call {
	return &MockService_GetMessageByID_Call{Call: _e.mock.On("GetMessageByID", messageID)}
}

func (_c *MockService_GetMessageByID_Call) Run(run func(messageID string)) *MockService_GetMessageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetMessageByID_Call) Return(matrixMessage *MatrixMessage, err error) *MockService_GetMessageByID_Call {
	_c.Call.Return(matrixMessage, err)
	return _c
}

func (_c *MockService_GetMessageByID_Call) RunAndReturn(run func(messageID string) (*MatrixMessage, error)) *MockService_GetMessageByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomByID provides a mock function for the type MockService
func (_mock *MockService) GetRoomByID(id uint) (*MatrixRoom, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByID")
	}

	var r0 *MatrixRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*MatrixRoom, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *MatrixRoom); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetRoomByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomByID'
type MockService_GetRoomByID_Call struct {
	*mock.Call
}

// GetRoomByID is a helper method to define mock.On call
//   - id uint
func (_e *MockService_Expecter) GetRoomByID(id interface{}) *MockService_GetRoomByID_Call {
	return &MockService_GetRoomByID_Call{Call: _e.mock.On("GetRoomByID", id)}
}

func (_c *MockService_GetRoomByID_Call) Run(run func(id uint)) *MockService_GetRoomByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetRoomByID_Call) Return(matrixRoom *MatrixRoom, err error) *MockService_GetRoomByID_Call {
	_c.Call.Return(matrixRoom, err)
	return _c
}

func (_c *MockService_GetRoomByID_Call) RunAndReturn(run func(id uint) (*MatrixRoom, error)) *MockService_GetRoomByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomByRoomID provides a mock function for the type MockService
func (_mock *MockService) GetRoomByRoomID(roomID string) (*MatrixRoom, error) {
	ret := _mock.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByRoomID")
	}

	var r0 *MatrixRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*MatrixRoom, error)); ok {
		return returnFunc(roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *MatrixRoom); ok {
		r0 = returnFunc(roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetRoomByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomByRoomID'
type MockService_GetRoomByRoomID_Call struct {
	*mock.Call
}

// GetRoomByRoomID is a helper method to define mock.On call
//   - roomID string
func (_e *MockService_Expecter) GetRoomByRoomID(roomID interface{}) *MockService_GetRoomByRoomID_Call {
	return &MockService_GetRoomByRoomID_Call{Call: _e.mock.On("GetRoomByRoomID", roomID)}
}

func (_c *MockService_GetRoomByRoomID_Call) Run(run func(roomID string)) *MockService_GetRoomByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetRoomByRoomID_Call) Return(matrixRoom *MatrixRoom, err error) *MockService_GetRoomByRoomID_Call {
	_c.Call.Return(matrixRoom, err)
	return _c
}

func (_c *MockService_GetRoomByRoomID_Call) RunAndReturn(run func(roomID string) (*MatrixRoom, error)) *MockService_GetRoomByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoomCount provides a mock function for the type MockService
func (_mock *MockService) GetRoomCount() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRoomCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetRoomCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoomCount'
type MockService_GetRoomCount_Call struct {
	*mock.Call
}

// GetRoomCount is a helper method to define mock.On call
func (_e *MockService_Expecter) GetRoomCount() *MockService_GetRoomCount_Call {
	return &MockService_GetRoomCount_Call{Call: _e.mock.On("GetRoomCount")}
}

func (_c *MockService_GetRoomCount_Call) Run(run func()) *MockService_GetRoomCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetRoomCount_Call) Return(n int64, err error) *MockService_GetRoomCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_GetRoomCount_Call) RunAndReturn(run func() (int64, error)) *MockService_GetRoomCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockService
func (_mock *MockService) GetUserByID(userID string) (*MatrixUser, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *MatrixUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*MatrixUser, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *MatrixUser); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - userID string
func (_e *MockService_Expecter) GetUserByID(userID interface{}) *MockService_GetUserByID_Call {
	return &MockService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", userID)}
}

func (_c *MockService_GetUserByID_Call) Run(run func(userID string)) *MockService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetUserByID_Call) Return(matrixUser *MatrixUser, err error) *MockService_GetUserByID_Call {
	_c.Call.Return(matrixUser, err)
	return _c
}

func (_c *MockService_GetUserByID_Call) RunAndReturn(run func(userID string) (*MatrixUser, error)) *MockService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListInputRoomsByChannel provides a mock function for the type MockService
func (_mock *MockService) ListInputRoomsByChannel(channelID uint) ([]MatrixRoom, error) {
	ret := _mock.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListInputRoomsByChannel")
	}

	var r0 []MatrixRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]MatrixRoom, error)); ok {
		return returnFunc(channelID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []MatrixRoom); ok {
		r0 = returnFunc(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MatrixRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(channelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListInputRoomsByChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInputRoomsByChannel'
type MockService_ListInputRoomsByChannel_Call struct {
	*mock.Call
}

// ListInputRoomsByChannel is a helper method to define mock.On call
//   - channelID uint
func (_e *MockService_Expecter) ListInputRoomsByChannel(channelID interface{}) *MockService_ListInputRoomsByChannel_Call {
	return &MockService_ListInputRoomsByChannel_Call{Call: _e.mock.On("ListInputRoomsByChannel", channelID)}
}

func (_c *MockService_ListInputRoomsByChannel_Call) Run(run func(channelID uint)) *MockService_ListInputRoomsByChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListInputRoomsByChannel_Call) Return(matrixRooms []MatrixRoom, err error) *MockService_ListInputRoomsByChannel_Call {
	_c.Call.Return(matrixRooms, err)
	return _c
}

func (_c *MockService_ListInputRoomsByChannel_Call) RunAndReturn(run func(channelID uint) ([]MatrixRoom, error)) *MockService_ListInputRoomsByChannel_Call {
	_c.Call.Return(run)
	return _c
}

// ListMessages provides a mock function for the type MockService
func (_mock *MockService) ListMessages(opts ListMessageOpts) ([]MatrixMessage, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for ListMessages")
	}

	var r0 []MatrixMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ListMessageOpts) ([]MatrixMessage, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(ListMessageOpts) []MatrixMessage); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MatrixMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ListMessageOpts) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMessages'
type MockService_ListMessages_Call struct {
	*mock.Call
}

// ListMessages is a helper method to define mock.On call
//   - opts ListMessageOpts
func (_e *MockService_Expecter) ListMessages(opts interface{}) *MockService_ListMessages_Call {
	return &MockService_ListMessages_Call{Call: _e.mock.On("ListMessages", opts)}
}

func (_c *MockService_ListMessages_Call) Run(run func(opts ListMessageOpts)) *MockService_ListMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ListMessageOpts
		if args[0] != nil {
			arg0 = args[0].(ListMessageOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListMessages_Call) Return(matrixMessages []MatrixMessage, err error) *MockService_ListMessages_Call {
	_c.Call.Return(matrixMessages, err)
	return _c
}

func (_c *MockService_ListMessages_Call) RunAndReturn(run func(opts ListMessageOpts) ([]MatrixMessage, error)) *MockService_ListMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListOutputRoomsByChannel provides a mock function for the type MockService
func (_mock *MockService) ListOutputRoomsByChannel(channelID uint) ([]MatrixRoom, error) {
	ret := _mock.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListOutputRoomsByChannel")
	}

	var r0 []MatrixRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]MatrixRoom, error)); ok {
		return returnFunc(channelID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []MatrixRoom); ok {
		r0 = returnFunc(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]MatrixRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(channelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListOutputRoomsByChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOutputRoomsByChannel'
type MockService_ListOutputRoomsByChannel_Call struct {
	*mock.Call
}

// ListOutputRoomsByChannel is a helper method to define mock.On call
//   - channelID uint
func (_e *MockService_Expecter) ListOutputRoomsByChannel(channelID interface{}) *MockService_ListOutputRoomsByChannel_Call {
	return &MockService_ListOutputRoomsByChannel_Call{Call: _e.mock.On("ListOutputRoomsByChannel", channelID)}
}

func (_c *MockService_ListOutputRoomsByChannel_Call) Run(run func(channelID uint)) *MockService_ListOutputRoomsByChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListOutputRoomsByChannel_Call) Return(matrixRooms []MatrixRoom, err error) *MockService_ListOutputRoomsByChannel_Call {
	_c.Call.Return(matrixRooms, err)
	return _c
}

func (_c *MockService_ListOutputRoomsByChannel_Call) RunAndReturn(run func(channelID uint) ([]MatrixRoom, error)) *MockService_ListOutputRoomsByChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewEvent provides a mock function for the type MockService
func (_mock *MockService) NewEvent(event *MatrixEvent) (*MatrixEvent, error) {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for NewEvent")
	}

	var r0 *MatrixEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*MatrixEvent) (*MatrixEvent, error)); ok {
		return returnFunc(event)
	}
	if returnFunc, ok := ret.Get(0).(func(*MatrixEvent) *MatrixEvent); ok {
		r0 = returnFunc(event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*MatrixEvent) error); ok {
		r1 = returnFunc(event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewEvent'
type MockService_NewEvent_Call struct {
	*mock.Call
}

// NewEvent is a helper method to define mock.On call
//   - event *MatrixEvent
func (_e *MockService_Expecter) NewEvent(event interface{}) *MockService_NewEvent_Call {
	return &MockService_NewEvent_Call{Call: _e.mock.On("NewEvent", event)}
}

func (_c *MockService_NewEvent_Call) Run(run func(event *MatrixEvent)) *MockService_NewEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *MatrixEvent
		if args[0] != nil {
			arg0 = args[0].(*MatrixEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewEvent_Call) Return(matrixEvent *MatrixEvent, err error) *MockService_NewEvent_Call {
	_c.Call.Return(matrixEvent, err)
	return _c
}

func (_c *MockService_NewEvent_Call) RunAndReturn(run func(event *MatrixEvent) (*MatrixEvent, error)) *MockService_NewEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessage provides a mock function for the type MockService
func (_mock *MockService) NewMessage(message *MatrixMessage) (*MatrixMessage, error) {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for NewMessage")
	}

	var r0 *MatrixMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*MatrixMessage) (*MatrixMessage, error)); ok {
		return returnFunc(message)
	}
	if returnFunc, ok := ret.Get(0).(func(*MatrixMessage) *MatrixMessage); ok {
		r0 = returnFunc(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*MatrixMessage) error); ok {
		r1 = returnFunc(message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMessage'
type MockService_NewMessage_Call struct {
	*mock.Call
}

// NewMessage is a helper method to define mock.On call
//   - message *MatrixMessage
func (_e *MockService_Expecter) NewMessage(message interface{}) *MockService_NewMessage_Call {
	return &MockService_NewMessage_Call{Call: _e.mock.On("NewMessage", message)}
}

func (_c *MockService_NewMessage_Call) Run(run func(message *MatrixMessage)) *MockService_NewMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *MatrixMessage
		if args[0] != nil {
			arg0 = args[0].(*MatrixMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewMessage_Call) Return(matrixMessage *MatrixMessage, err error) *MockService_NewMessage_Call {
	_c.Call.Return(matrixMessage, err)
	return _c
}

func (_c *MockService_NewMessage_Call) RunAndReturn(run func(message *MatrixMessage) (*MatrixMessage, error)) *MockService_NewMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewRoom provides a mock function for the type MockService
func (_mock *MockService) NewRoom(room *MatrixRoom) (*MatrixRoom, error) {
	ret := _mock.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for NewRoom")
	}

	var r0 *MatrixRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*MatrixRoom) (*MatrixRoom, error)); ok {
		return returnFunc(room)
	}
	if returnFunc, ok := ret.Get(0).(func(*MatrixRoom) *MatrixRoom); ok {
		r0 = returnFunc(room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*MatrixRoom) error); ok {
		r1 = returnFunc(room)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRoom'
type MockService_NewRoom_Call struct {
	*mock.Call
}

// NewRoom is a helper method to define mock.On call
//   - room *MatrixRoom
func (_e *MockService_Expecter) NewRoom(room interface{}) *MockService_NewRoom_Call {
	return &MockService_NewRoom_Call{Call: _e.mock.On("NewRoom", room)}
}

func (_c *MockService_NewRoom_Call) Run(run func(room *MatrixRoom)) *MockService_NewRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *MatrixRoom
		if args[0] != nil {
			arg0 = args[0].(*MatrixRoom)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewRoom_Call) Return(matrixRoom *MatrixRoom, err error) *MockService_NewRoom_Call {
	_c.Call.Return(matrixRoom, err)
	return _c
}

func (_c *MockService_NewRoom_Call) RunAndReturn(run func(room *MatrixRoom) (*MatrixRoom, error)) *MockService_NewRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewUser provides a mock function for the type MockService
func (_mock *MockService) NewUser(user *MatrixUser) (*MatrixUser, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for NewUser")
	}

	var r0 *MatrixUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*MatrixUser) (*MatrixUser, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*MatrixUser) *MatrixUser); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*MatrixUser) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUser'
type MockService_NewUser_Call struct {
	*mock.Call
}

// NewUser is a helper method to define mock.On call
//   - user *MatrixUser
func (_e *MockService_Expecter) NewUser(user interface{}) *MockService_NewUser_Call {
	return &MockService_NewUser_Call{Call: _e.mock.On("NewUser", user)}
}

func (_c *MockService_NewUser_Call) Run(run func(user *MatrixUser)) *MockService_NewUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *MatrixUser
		if args[0] != nil {
			arg0 = args[0].(*MatrixUser)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewUser_Call) Return(matrixUser *MatrixUser, err error) *MockService_NewUser_Call {
	_c.Call.Return(matrixUser, err)
	return _c
}

func (_c *MockService_NewUser_Call) RunAndReturn(run func(user *MatrixUser) (*MatrixUser, error)) *MockService_NewUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveDanglingUsers provides a mock function for the type MockService
func (_mock *MockService) RemoveDanglingUsers() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoveDanglingUsers")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RemoveDanglingUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDanglingUsers'
type MockService_RemoveDanglingUsers_Call struct {
	*mock.Call
}

// RemoveDanglingUsers is a helper method to define mock.On call
func (_e *MockService_Expecter) RemoveDanglingUsers() *MockService_RemoveDanglingUsers_Call {
	return &MockService_RemoveDanglingUsers_Call{Call: _e.mock.On("RemoveDanglingUsers")}
}

func (_c *MockService_RemoveDanglingUsers_Call) Run(run func()) *MockService_RemoveDanglingUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_RemoveDanglingUsers_Call) Return(n int64, err error) *MockService_RemoveDanglingUsers_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_RemoveDanglingUsers_Call) RunAndReturn(run func() (int64, error)) *MockService_RemoveDanglingUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoom provides a mock function for the type MockService
func (_mock *MockService) UpdateRoom(room *MatrixRoom) (*MatrixRoom, error) {
	ret := _mock.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 *MatrixRoom
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*MatrixRoom) (*MatrixRoom, error)); ok {
		return returnFunc(room)
	}
	if returnFunc, ok := ret.Get(0).(func(*MatrixRoom) *MatrixRoom); ok {
		r0 = returnFunc(room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MatrixRoom)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*MatrixRoom) error); ok {
		r1 = returnFunc(room)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoom'
type MockService_UpdateRoom_Call struct {
	*mock.Call
}

// UpdateRoom is a helper method to define mock.On call
//   - room *MatrixRoom
func (_e *MockService_Expecter) UpdateRoom(room interface{}) *MockService_UpdateRoom_Call {
	return &MockService_UpdateRoom_Call{Call: _e.mock.On("UpdateRoom", room)}
}

func (_c *MockService_UpdateRoom_Call) Run(run func(room *MatrixRoom)) *MockService_UpdateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *MatrixRoom
		if args[0] != nil {
			arg0 = args[0].(*MatrixRoom)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_UpdateRoom_Call) Return(matrixRoom *MatrixRoom, err error) *MockService_UpdateRoom_Call {
	_c.Call.Return(matrixRoom, err)
	return _c
}

func (_c *MockService_UpdateRoom_Call) RunAndReturn(run func(room *MatrixRoom) (*MatrixRoom, error)) *MockService_UpdateRoom_Call {
	_c.Call.Return(run)
	return _c
}
