// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/matrix (interfaces: MessageAction)

// Package matrix is a generated GoMock package.
package matrix

import (
	reflect "reflect"
	regexp "regexp"

	gomock "github.com/golang/mock/gomock"
)

// MockMessageAction is a mock of MessageAction interface.
type MockMessageAction struct {
	ctrl     *gomock.Controller
	recorder *MockMessageActionMockRecorder
}

// MockMessageActionMockRecorder is the mock recorder for MockMessageAction.
type MockMessageActionMockRecorder struct {
	mock *MockMessageAction
}

// NewMockMessageAction creates a new mock instance.
func NewMockMessageAction(ctrl *gomock.Controller) *MockMessageAction {
	mock := &MockMessageAction{ctrl: ctrl}
	mock.recorder = &MockMessageActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageAction) EXPECT() *MockMessageActionMockRecorder {
	return m.recorder
}

// HandleEvent mocks base method.
func (m *MockMessageAction) HandleEvent(arg0 *MessageEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleEvent", arg0)
}

// HandleEvent indicates an expected call of HandleEvent.
func (mr *MockMessageActionMockRecorder) HandleEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEvent", reflect.TypeOf((*MockMessageAction)(nil).HandleEvent), arg0)
}

// Name mocks base method.
func (m *MockMessageAction) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMessageActionMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMessageAction)(nil).Name))
}

// Selector mocks base method.
func (m *MockMessageAction) Selector() *regexp.Regexp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selector")
	ret0, _ := ret[0].(*regexp.Regexp)
	return ret0
}

// Selector indicates an expected call of Selector.
func (mr *MockMessageActionMockRecorder) Selector() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selector", reflect.TypeOf((*MockMessageAction)(nil).Selector))
}
