// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package matrix

import (
	"log/slog"

	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/matrix/database"
	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/matrix/mautrixcl"
	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/matrix/messenger"
	database0 "github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReactionAction creates a new instance of MockReactionAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReactionAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReactionAction {
	mock := &MockReactionAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReactionAction is an autogenerated mock type for the ReactionAction type
type MockReactionAction struct {
	mock.Mock
}

type MockReactionAction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReactionAction) EXPECT() *MockReactionAction_Expecter {
	return &MockReactionAction_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function for the type MockReactionAction
func (_mock *MockReactionAction) Configure(logger *slog.Logger, client mautrixcl.Client, messenger1 messenger.Messenger, matrixDB database.Service, db database0.Service, bridgeServices *BridgeServices) {
	_mock.Called(logger, client, messenger1, matrixDB, db, bridgeServices)
	return
}

// MockReactionAction_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockReactionAction_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - logger *slog.Logger
//   - client mautrixcl.Client
//   - messenger1 messenger.Messenger
//   - matrixDB database.Service
//   - db database0.Service
//   - bridgeServices *BridgeServices
func (_e *MockReactionAction_Expecter) Configure(logger interface{}, client interface{}, messenger1 interface{}, matrixDB interface{}, db interface{}, bridgeServices interface{}) *MockReactionAction_Configure_Call {
	return &MockReactionAction_Configure_Call{Call: _e.mock.On("Configure", logger, client, messenger1, matrixDB, db, bridgeServices)}
}

func (_c *MockReactionAction_Configure_Call) Run(run func(logger *slog.Logger, client mautrixcl.Client, messenger1 messenger.Messenger, matrixDB database.Service, db database0.Service, bridgeServices *BridgeServices)) *MockReactionAction_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *slog.Logger
		if args[0] != nil {
			arg0 = args[0].(*slog.Logger)
		}
		var arg1 mautrixcl.Client
		if args[1] != nil {
			arg1 = args[1].(mautrixcl.Client)
		}
		var arg2 messenger.Messenger
		if args[2] != nil {
			arg2 = args[2].(messenger.Messenger)
		}
		var arg3 database.Service
		if args[3] != nil {
			arg3 = args[3].(database.Service)
		}
		var arg4 database0.Service
		if args[4] != nil {
			arg4 = args[4].(database0.Service)
		}
		var arg5 *BridgeServices
		if args[5] != nil {
			arg5 = args[5].(*BridgeServices)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockReactionAction_Configure_Call) Return() *MockReactionAction_Configure_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReactionAction_Configure_Call) RunAndReturn(run func(logger *slog.Logger, client mautrixcl.Client, messenger1 messenger.Messenger, matrixDB database.Service, db database0.Service, bridgeServices *BridgeServices)) *MockReactionAction_Configure_Call {
	_c.Run(run)
	return _c
}

// HandleEvent provides a mock function for the type MockReactionAction
func (_mock *MockReactionAction) HandleEvent(event *ReactionEvent, reactionToMessage *database.MatrixMessage) {
	_mock.Called(event, reactionToMessage)
	return
}

// MockReactionAction_HandleEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleEvent'
type MockReactionAction_HandleEvent_Call struct {
	*mock.Call
}

// HandleEvent is a helper method to define mock.On call
//   - event *ReactionEvent
//   - reactionToMessage *database.MatrixMessage
func (_e *MockReactionAction_Expecter) HandleEvent(event interface{}, reactionToMessage interface{}) *MockReactionAction_HandleEvent_Call {
	return &MockReactionAction_HandleEvent_Call{Call: _e.mock.On("HandleEvent", event, reactionToMessage)}
}

func (_c *MockReactionAction_HandleEvent_Call) Run(run func(event *ReactionEvent, reactionToMessage *database.MatrixMessage)) *MockReactionAction_HandleEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ReactionEvent
		if args[0] != nil {
			arg0 = args[0].(*ReactionEvent)
		}
		var arg1 *database.MatrixMessage
		if args[1] != nil {
			arg1 = args[1].(*database.MatrixMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReactionAction_HandleEvent_Call) Return() *MockReactionAction_HandleEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReactionAction_HandleEvent_Call) RunAndReturn(run func(event *ReactionEvent, reactionToMessage *database.MatrixMessage)) *MockReactionAction_HandleEvent_Call {
	_c.Run(run)
	return _c
}

// Name provides a mock function for the type MockReactionAction
func (_mock *MockReactionAction) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReactionAction_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockReactionAction_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockReactionAction_Expecter) Name() *MockReactionAction_Name_Call {
	return &MockReactionAction_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockReactionAction_Name_Call) Run(run func()) *MockReactionAction_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReactionAction_Name_Call) Return(s string) *MockReactionAction_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReactionAction_Name_Call) RunAndReturn(run func() string) *MockReactionAction_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Selector provides a mock function for the type MockReactionAction
func (_mock *MockReactionAction) Selector() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Selector")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockReactionAction_Selector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Selector'
type MockReactionAction_Selector_Call struct {
	*mock.Call
}

// Selector is a helper method to define mock.On call
func (_e *MockReactionAction_Expecter) Selector() *MockReactionAction_Selector_Call {
	return &MockReactionAction_Selector_Call{Call: _e.mock.On("Selector")}
}

func (_c *MockReactionAction_Selector_Call) Run(run func()) *MockReactionAction_Selector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReactionAction_Selector_Call) Return(strings []string) *MockReactionAction_Selector_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockReactionAction_Selector_Call) RunAndReturn(run func() []string) *MockReactionAction_Selector_Call {
	_c.Call.Return(run)
	return _c
}
