// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package matrix

import (
	"log/slog"
	"regexp"

	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/matrix/database"
	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/matrix/mautrixcl"
	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/matrix/messenger"
	database0 "github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReplyAction creates a new instance of MockReplyAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplyAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplyAction {
	mock := &MockReplyAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReplyAction is an autogenerated mock type for the ReplyAction type
type MockReplyAction struct {
	mock.Mock
}

type MockReplyAction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplyAction) EXPECT() *MockReplyAction_Expecter {
	return &MockReplyAction_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function for the type MockReplyAction
func (_mock *MockReplyAction) Configure(logger *slog.Logger, client mautrixcl.Client, messenger1 messenger.Messenger, matrixDB database.Service, db database0.Service, bridgeServices *BridgeServices) {
	_mock.Called(logger, client, messenger1, matrixDB, db, bridgeServices)
	return
}

// MockReplyAction_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockReplyAction_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - logger *slog.Logger
//   - client mautrixcl.Client
//   - messenger1 messenger.Messenger
//   - matrixDB database.Service
//   - db database0.Service
//   - bridgeServices *BridgeServices
func (_e *MockReplyAction_Expecter) Configure(logger interface{}, client interface{}, messenger1 interface{}, matrixDB interface{}, db interface{}, bridgeServices interface{}) *MockReplyAction_Configure_Call {
	return &MockReplyAction_Configure_Call{Call: _e.mock.On("Configure", logger, client, messenger1, matrixDB, db, bridgeServices)}
}

func (_c *MockReplyAction_Configure_Call) Run(run func(logger *slog.Logger, client mautrixcl.Client, messenger1 messenger.Messenger, matrixDB database.Service, db database0.Service, bridgeServices *BridgeServices)) *MockReplyAction_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *slog.Logger
		if args[0] != nil {
			arg0 = args[0].(*slog.Logger)
		}
		var arg1 mautrixcl.Client
		if args[1] != nil {
			arg1 = args[1].(mautrixcl.Client)
		}
		var arg2 messenger.Messenger
		if args[2] != nil {
			arg2 = args[2].(messenger.Messenger)
		}
		var arg3 database.Service
		if args[3] != nil {
			arg3 = args[3].(database.Service)
		}
		var arg4 database0.Service
		if args[4] != nil {
			arg4 = args[4].(database0.Service)
		}
		var arg5 *BridgeServices
		if args[5] != nil {
			arg5 = args[5].(*BridgeServices)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockReplyAction_Configure_Call) Return() *MockReplyAction_Configure_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReplyAction_Configure_Call) RunAndReturn(run func(logger *slog.Logger, client mautrixcl.Client, messenger1 messenger.Messenger, matrixDB database.Service, db database0.Service, bridgeServices *BridgeServices)) *MockReplyAction_Configure_Call {
	_c.Run(run)
	return _c
}

// HandleEvent provides a mock function for the type MockReplyAction
func (_mock *MockReplyAction) HandleEvent(event *MessageEvent, replyToMessage *database.MatrixMessage) {
	_mock.Called(event, replyToMessage)
	return
}

// MockReplyAction_HandleEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleEvent'
type MockReplyAction_HandleEvent_Call struct {
	*mock.Call
}

// HandleEvent is a helper method to define mock.On call
//   - event *MessageEvent
//   - replyToMessage *database.MatrixMessage
func (_e *MockReplyAction_Expecter) HandleEvent(event interface{}, replyToMessage interface{}) *MockReplyAction_HandleEvent_Call {
	return &MockReplyAction_HandleEvent_Call{Call: _e.mock.On("HandleEvent", event, replyToMessage)}
}

func (_c *MockReplyAction_HandleEvent_Call) Run(run func(event *MessageEvent, replyToMessage *database.MatrixMessage)) *MockReplyAction_HandleEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *MessageEvent
		if args[0] != nil {
			arg0 = args[0].(*MessageEvent)
		}
		var arg1 *database.MatrixMessage
		if args[1] != nil {
			arg1 = args[1].(*database.MatrixMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReplyAction_HandleEvent_Call) Return() *MockReplyAction_HandleEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReplyAction_HandleEvent_Call) RunAndReturn(run func(event *MessageEvent, replyToMessage *database.MatrixMessage)) *MockReplyAction_HandleEvent_Call {
	_c.Run(run)
	return _c
}

// Name provides a mock function for the type MockReplyAction
func (_mock *MockReplyAction) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReplyAction_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockReplyAction_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockReplyAction_Expecter) Name() *MockReplyAction_Name_Call {
	return &MockReplyAction_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockReplyAction_Name_Call) Run(run func()) *MockReplyAction_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyAction_Name_Call) Return(s string) *MockReplyAction_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReplyAction_Name_Call) RunAndReturn(run func() string) *MockReplyAction_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Selector provides a mock function for the type MockReplyAction
func (_mock *MockReplyAction) Selector() *regexp.Regexp {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Selector")
	}

	var r0 *regexp.Regexp
	if returnFunc, ok := ret.Get(0).(func() *regexp.Regexp); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*regexp.Regexp)
		}
	}
	return r0
}

// MockReplyAction_Selector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Selector'
type MockReplyAction_Selector_Call struct {
	*mock.Call
}

// Selector is a helper method to define mock.On call
func (_e *MockReplyAction_Expecter) Selector() *MockReplyAction_Selector_Call {
	return &MockReplyAction_Selector_Call{Call: _e.mock.On("Selector")}
}

func (_c *MockReplyAction_Selector_Call) Run(run func()) *MockReplyAction_Selector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyAction_Selector_Call) Return(regexp1 *regexp.Regexp) *MockReplyAction_Selector_Call {
	_c.Call.Return(regexp1)
	return _c
}

func (_c *MockReplyAction_Selector_Call) RunAndReturn(run func() *regexp.Regexp) *MockReplyAction_Selector_Call {
	_c.Call.Return(run)
	return _c
}
