// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// DeleteIcalInput provides a mock function for the type MockService
func (_mock *MockService) DeleteIcalInput(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIcalInput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteIcalInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIcalInput'
type MockService_DeleteIcalInput_Call struct {
	*mock.Call
}

// DeleteIcalInput is a helper method to define mock.On call
//   - id uint
func (_e *MockService_Expecter) DeleteIcalInput(id interface{}) *MockService_DeleteIcalInput_Call {
	return &MockService_DeleteIcalInput_Call{Call: _e.mock.On("DeleteIcalInput", id)}
}

func (_c *MockService_DeleteIcalInput_Call) Run(run func(id uint)) *MockService_DeleteIcalInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteIcalInput_Call) Return(err error) *MockService_DeleteIcalInput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteIcalInput_Call) RunAndReturn(run func(id uint) error) *MockService_DeleteIcalInput_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIcalOutput provides a mock function for the type MockService
func (_mock *MockService) DeleteIcalOutput(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIcalOutput")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteIcalOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIcalOutput'
type MockService_DeleteIcalOutput_Call struct {
	*mock.Call
}

// DeleteIcalOutput is a helper method to define mock.On call
//   - id uint
func (_e *MockService_Expecter) DeleteIcalOutput(id interface{}) *MockService_DeleteIcalOutput_Call {
	return &MockService_DeleteIcalOutput_Call{Call: _e.mock.On("DeleteIcalOutput", id)}
}

func (_c *MockService_DeleteIcalOutput_Call) Run(run func(id uint)) *MockService_DeleteIcalOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_DeleteIcalOutput_Call) Return(err error) *MockService_DeleteIcalOutput_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteIcalOutput_Call) RunAndReturn(run func(id uint) error) *MockService_DeleteIcalOutput_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateNewToken provides a mock function for the type MockService
func (_mock *MockService) GenerateNewToken(icalOutput *IcalOutput) (*IcalOutput, error) {
	ret := _mock.Called(icalOutput)

	if len(ret) == 0 {
		panic("no return value specified for GenerateNewToken")
	}

	var r0 *IcalOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*IcalOutput) (*IcalOutput, error)); ok {
		return returnFunc(icalOutput)
	}
	if returnFunc, ok := ret.Get(0).(func(*IcalOutput) *IcalOutput); ok {
		r0 = returnFunc(icalOutput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IcalOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*IcalOutput) error); ok {
		r1 = returnFunc(icalOutput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GenerateNewToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateNewToken'
type MockService_GenerateNewToken_Call struct {
	*mock.Call
}

// GenerateNewToken is a helper method to define mock.On call
//   - icalOutput *IcalOutput
func (_e *MockService_Expecter) GenerateNewToken(icalOutput interface{}) *MockService_GenerateNewToken_Call {
	return &MockService_GenerateNewToken_Call{Call: _e.mock.On("GenerateNewToken", icalOutput)}
}

func (_c *MockService_GenerateNewToken_Call) Run(run func(icalOutput *IcalOutput)) *MockService_GenerateNewToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *IcalOutput
		if args[0] != nil {
			arg0 = args[0].(*IcalOutput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GenerateNewToken_Call) Return(icalOutput1 *IcalOutput, err error) *MockService_GenerateNewToken_Call {
	_c.Call.Return(icalOutput1, err)
	return _c
}

func (_c *MockService_GenerateNewToken_Call) RunAndReturn(run func(icalOutput *IcalOutput) (*IcalOutput, error)) *MockService_GenerateNewToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetIcalInputByID provides a mock function for the type MockService
func (_mock *MockService) GetIcalInputByID(id uint) (*IcalInput, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetIcalInputByID")
	}

	var r0 *IcalInput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*IcalInput, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *IcalInput); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IcalInput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetIcalInputByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIcalInputByID'
type MockService_GetIcalInputByID_Call struct {
	*mock.Call
}

// GetIcalInputByID is a helper method to define mock.On call
//   - id uint
func (_e *MockService_Expecter) GetIcalInputByID(id interface{}) *MockService_GetIcalInputByID_Call {
	return &MockService_GetIcalInputByID_Call{Call: _e.mock.On("GetIcalInputByID", id)}
}

func (_c *MockService_GetIcalInputByID_Call) Run(run func(id uint)) *MockService_GetIcalInputByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetIcalInputByID_Call) Return(icalInput *IcalInput, err error) *MockService_GetIcalInputByID_Call {
	_c.Call.Return(icalInput, err)
	return _c
}

func (_c *MockService_GetIcalInputByID_Call) RunAndReturn(run func(id uint) (*IcalInput, error)) *MockService_GetIcalInputByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetIcalOutputByID provides a mock function for the type MockService
func (_mock *MockService) GetIcalOutputByID(id uint) (*IcalOutput, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetIcalOutputByID")
	}

	var r0 *IcalOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*IcalOutput, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *IcalOutput); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IcalOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetIcalOutputByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIcalOutputByID'
type MockService_GetIcalOutputByID_Call struct {
	*mock.Call
}

// GetIcalOutputByID is a helper method to define mock.On call
//   - id uint
func (_e *MockService_Expecter) GetIcalOutputByID(id interface{}) *MockService_GetIcalOutputByID_Call {
	return &MockService_GetIcalOutputByID_Call{Call: _e.mock.On("GetIcalOutputByID", id)}
}

func (_c *MockService_GetIcalOutputByID_Call) Run(run func(id uint)) *MockService_GetIcalOutputByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetIcalOutputByID_Call) Return(icalOutput *IcalOutput, err error) *MockService_GetIcalOutputByID_Call {
	_c.Call.Return(icalOutput, err)
	return _c
}

func (_c *MockService_GetIcalOutputByID_Call) RunAndReturn(run func(id uint) (*IcalOutput, error)) *MockService_GetIcalOutputByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListIcalInputs provides a mock function for the type MockService
func (_mock *MockService) ListIcalInputs(listIcalInputsOpts *ListIcalInputsOpts) ([]IcalInput, error) {
	ret := _mock.Called(listIcalInputsOpts)

	if len(ret) == 0 {
		panic("no return value specified for ListIcalInputs")
	}

	var r0 []IcalInput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ListIcalInputsOpts) ([]IcalInput, error)); ok {
		return returnFunc(listIcalInputsOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(*ListIcalInputsOpts) []IcalInput); ok {
		r0 = returnFunc(listIcalInputsOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]IcalInput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ListIcalInputsOpts) error); ok {
		r1 = returnFunc(listIcalInputsOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListIcalInputs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIcalInputs'
type MockService_ListIcalInputs_Call struct {
	*mock.Call
}

// ListIcalInputs is a helper method to define mock.On call
//   - listIcalInputsOpts *ListIcalInputsOpts
func (_e *MockService_Expecter) ListIcalInputs(listIcalInputsOpts interface{}) *MockService_ListIcalInputs_Call {
	return &MockService_ListIcalInputs_Call{Call: _e.mock.On("ListIcalInputs", listIcalInputsOpts)}
}

func (_c *MockService_ListIcalInputs_Call) Run(run func(listIcalInputsOpts *ListIcalInputsOpts)) *MockService_ListIcalInputs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ListIcalInputsOpts
		if args[0] != nil {
			arg0 = args[0].(*ListIcalInputsOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListIcalInputs_Call) Return(icalInputs []IcalInput, err error) *MockService_ListIcalInputs_Call {
	_c.Call.Return(icalInputs, err)
	return _c
}

func (_c *MockService_ListIcalInputs_Call) RunAndReturn(run func(listIcalInputsOpts *ListIcalInputsOpts) ([]IcalInput, error)) *MockService_ListIcalInputs_Call {
	_c.Call.Return(run)
	return _c
}

// NewIcalInput provides a mock function for the type MockService
func (_mock *MockService) NewIcalInput(icalInput *IcalInput) (*IcalInput, error) {
	ret := _mock.Called(icalInput)

	if len(ret) == 0 {
		panic("no return value specified for NewIcalInput")
	}

	var r0 *IcalInput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*IcalInput) (*IcalInput, error)); ok {
		return returnFunc(icalInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*IcalInput) *IcalInput); ok {
		r0 = returnFunc(icalInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IcalInput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*IcalInput) error); ok {
		r1 = returnFunc(icalInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewIcalInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewIcalInput'
type MockService_NewIcalInput_Call struct {
	*mock.Call
}

// NewIcalInput is a helper method to define mock.On call
//   - icalInput *IcalInput
func (_e *MockService_Expecter) NewIcalInput(icalInput interface{}) *MockService_NewIcalInput_Call {
	return &MockService_NewIcalInput_Call{Call: _e.mock.On("NewIcalInput", icalInput)}
}

func (_c *MockService_NewIcalInput_Call) Run(run func(icalInput *IcalInput)) *MockService_NewIcalInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *IcalInput
		if args[0] != nil {
			arg0 = args[0].(*IcalInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewIcalInput_Call) Return(icalInput1 *IcalInput, err error) *MockService_NewIcalInput_Call {
	_c.Call.Return(icalInput1, err)
	return _c
}

func (_c *MockService_NewIcalInput_Call) RunAndReturn(run func(icalInput *IcalInput) (*IcalInput, error)) *MockService_NewIcalInput_Call {
	_c.Call.Return(run)
	return _c
}

// NewIcalOutput provides a mock function for the type MockService
func (_mock *MockService) NewIcalOutput(icalOutput *IcalOutput) (*IcalOutput, error) {
	ret := _mock.Called(icalOutput)

	if len(ret) == 0 {
		panic("no return value specified for NewIcalOutput")
	}

	var r0 *IcalOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*IcalOutput) (*IcalOutput, error)); ok {
		return returnFunc(icalOutput)
	}
	if returnFunc, ok := ret.Get(0).(func(*IcalOutput) *IcalOutput); ok {
		r0 = returnFunc(icalOutput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IcalOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*IcalOutput) error); ok {
		r1 = returnFunc(icalOutput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewIcalOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewIcalOutput'
type MockService_NewIcalOutput_Call struct {
	*mock.Call
}

// NewIcalOutput is a helper method to define mock.On call
//   - icalOutput *IcalOutput
func (_e *MockService_Expecter) NewIcalOutput(icalOutput interface{}) *MockService_NewIcalOutput_Call {
	return &MockService_NewIcalOutput_Call{Call: _e.mock.On("NewIcalOutput", icalOutput)}
}

func (_c *MockService_NewIcalOutput_Call) Run(run func(icalOutput *IcalOutput)) *MockService_NewIcalOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *IcalOutput
		if args[0] != nil {
			arg0 = args[0].(*IcalOutput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewIcalOutput_Call) Return(icalOutput1 *IcalOutput, err error) *MockService_NewIcalOutput_Call {
	_c.Call.Return(icalOutput1, err)
	return _c
}

func (_c *MockService_NewIcalOutput_Call) RunAndReturn(run func(icalOutput *IcalOutput) (*IcalOutput, error)) *MockService_NewIcalOutput_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIcalInput provides a mock function for the type MockService
func (_mock *MockService) UpdateIcalInput(entity *IcalInput) (*IcalInput, error) {
	ret := _mock.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIcalInput")
	}

	var r0 *IcalInput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*IcalInput) (*IcalInput, error)); ok {
		return returnFunc(entity)
	}
	if returnFunc, ok := ret.Get(0).(func(*IcalInput) *IcalInput); ok {
		r0 = returnFunc(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IcalInput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*IcalInput) error); ok {
		r1 = returnFunc(entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateIcalInput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIcalInput'
type MockService_UpdateIcalInput_Call struct {
	*mock.Call
}

// UpdateIcalInput is a helper method to define mock.On call
//   - entity *IcalInput
func (_e *MockService_Expecter) UpdateIcalInput(entity interface{}) *MockService_UpdateIcalInput_Call {
	return &MockService_UpdateIcalInput_Call{Call: _e.mock.On("UpdateIcalInput", entity)}
}

func (_c *MockService_UpdateIcalInput_Call) Run(run func(entity *IcalInput)) *MockService_UpdateIcalInput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *IcalInput
		if args[0] != nil {
			arg0 = args[0].(*IcalInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_UpdateIcalInput_Call) Return(icalInput *IcalInput, err error) *MockService_UpdateIcalInput_Call {
	_c.Call.Return(icalInput, err)
	return _c
}

func (_c *MockService_UpdateIcalInput_Call) RunAndReturn(run func(entity *IcalInput) (*IcalInput, error)) *MockService_UpdateIcalInput_Call {
	_c.Call.Return(run)
	return _c
}
