// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ical

import (
	"time"

	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/connectors/ical/database"
	"github.com/CubicrootXYZ/matrix-reminder-and-calendar-bot/internal/daemon"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type MockService
func (_mock *MockService) Cleanup() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockService_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockService_Expecter) Cleanup() *MockService_Cleanup_Call {
	return &MockService_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockService_Cleanup_Call) Run(run func()) *MockService_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Cleanup_Call) Return(err error) *MockService_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Cleanup_Call) RunAndReturn(run func() error) *MockService_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// GetOutput provides a mock function for the type MockService
func (_mock *MockService) GetOutput(outputID uint, regenToken bool) (*database.IcalOutput, string, error) {
	ret := _mock.Called(outputID, regenToken)

	if len(ret) == 0 {
		panic("no return value specified for GetOutput")
	}

	var r0 *database.IcalOutput
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uint, bool) (*database.IcalOutput, string, error)); ok {
		return returnFunc(outputID, regenToken)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, bool) *database.IcalOutput); ok {
		r0 = returnFunc(outputID, regenToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.IcalOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, bool) string); ok {
		r1 = returnFunc(outputID, regenToken)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uint, bool) error); ok {
		r2 = returnFunc(outputID, regenToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOutput'
type MockService_GetOutput_Call struct {
	*mock.Call
}

// GetOutput is a helper method to define mock.On call
//   - outputID uint
//   - regenToken bool
func (_e *MockService_Expecter) GetOutput(outputID interface{}, regenToken interface{}) *MockService_GetOutput_Call {
	return &MockService_GetOutput_Call{Call: _e.mock.On("GetOutput", outputID, regenToken)}
}

func (_c *MockService_GetOutput_Call) Run(run func(outputID uint, regenToken bool)) *MockService_GetOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOutput_Call) Return(icalOutput *database.IcalOutput, s string, err error) *MockService_GetOutput_Call {
	_c.Call.Return(icalOutput, s, err)
	return _c
}

func (_c *MockService_GetOutput_Call) RunAndReturn(run func(outputID uint, regenToken bool) (*database.IcalOutput, string, error)) *MockService_GetOutput_Call {
	_c.Call.Return(run)
	return _c
}

// InputRemoved provides a mock function for the type MockService
func (_mock *MockService) InputRemoved(inputType string, inputID uint) error {
	ret := _mock.Called(inputType, inputID)

	if len(ret) == 0 {
		panic("no return value specified for InputRemoved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = returnFunc(inputType, inputID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_InputRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InputRemoved'
type MockService_InputRemoved_Call struct {
	*mock.Call
}

// InputRemoved is a helper method to define mock.On call
//   - inputType string
//   - inputID uint
func (_e *MockService_Expecter) InputRemoved(inputType interface{}, inputID interface{}) *MockService_InputRemoved_Call {
	return &MockService_InputRemoved_Call{Call: _e.mock.On("InputRemoved", inputType, inputID)}
}

func (_c *MockService_InputRemoved_Call) Run(run func(inputType string, inputID uint)) *MockService_InputRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_InputRemoved_Call) Return(err error) *MockService_InputRemoved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_InputRemoved_Call) RunAndReturn(run func(inputType string, inputID uint) error) *MockService_InputRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutput provides a mock function for the type MockService
func (_mock *MockService) NewOutput(channelID uint) (*database.IcalOutput, string, error) {
	ret := _mock.Called(channelID)

	if len(ret) == 0 {
		panic("no return value specified for NewOutput")
	}

	var r0 *database.IcalOutput
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*database.IcalOutput, string, error)); ok {
		return returnFunc(channelID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *database.IcalOutput); ok {
		r0 = returnFunc(channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.IcalOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) string); ok {
		r1 = returnFunc(channelID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uint) error); ok {
		r2 = returnFunc(channelID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_NewOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewOutput'
type MockService_NewOutput_Call struct {
	*mock.Call
}

// NewOutput is a helper method to define mock.On call
//   - channelID uint
func (_e *MockService_Expecter) NewOutput(channelID interface{}) *MockService_NewOutput_Call {
	return &MockService_NewOutput_Call{Call: _e.mock.On("NewOutput", channelID)}
}

func (_c *MockService_NewOutput_Call) Run(run func(channelID uint)) *MockService_NewOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_NewOutput_Call) Return(icalOutput *database.IcalOutput, s string, err error) *MockService_NewOutput_Call {
	_c.Call.Return(icalOutput, s, err)
	return _c
}

func (_c *MockService_NewOutput_Call) RunAndReturn(run func(channelID uint) (*database.IcalOutput, string, error)) *MockService_NewOutput_Call {
	_c.Call.Return(run)
	return _c
}

// OutputRemoved provides a mock function for the type MockService
func (_mock *MockService) OutputRemoved(outputType string, outputID uint) error {
	ret := _mock.Called(outputType, outputID)

	if len(ret) == 0 {
		panic("no return value specified for OutputRemoved")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = returnFunc(outputType, outputID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_OutputRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutputRemoved'
type MockService_OutputRemoved_Call struct {
	*mock.Call
}

// OutputRemoved is a helper method to define mock.On call
//   - outputType string
//   - outputID uint
func (_e *MockService_Expecter) OutputRemoved(outputType interface{}, outputID interface{}) *MockService_OutputRemoved_Call {
	return &MockService_OutputRemoved_Call{Call: _e.mock.On("OutputRemoved", outputType, outputID)}
}

func (_c *MockService_OutputRemoved_Call) Run(run func(outputType string, outputID uint)) *MockService_OutputRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_OutputRemoved_Call) Return(err error) *MockService_OutputRemoved_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_OutputRemoved_Call) RunAndReturn(run func(outputType string, outputID uint) error) *MockService_OutputRemoved_Call {
	_c.Call.Return(run)
	return _c
}

// SendDailyReminder provides a mock function for the type MockService
func (_mock *MockService) SendDailyReminder(dailyReminder *daemon.DailyReminder, output *daemon.Output) error {
	ret := _mock.Called(dailyReminder, output)

	if len(ret) == 0 {
		panic("no return value specified for SendDailyReminder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*daemon.DailyReminder, *daemon.Output) error); ok {
		r0 = returnFunc(dailyReminder, output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SendDailyReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDailyReminder'
type MockService_SendDailyReminder_Call struct {
	*mock.Call
}

// SendDailyReminder is a helper method to define mock.On call
//   - dailyReminder *daemon.DailyReminder
//   - output *daemon.Output
func (_e *MockService_Expecter) SendDailyReminder(dailyReminder interface{}, output interface{}) *MockService_SendDailyReminder_Call {
	return &MockService_SendDailyReminder_Call{Call: _e.mock.On("SendDailyReminder", dailyReminder, output)}
}

func (_c *MockService_SendDailyReminder_Call) Run(run func(dailyReminder *daemon.DailyReminder, output *daemon.Output)) *MockService_SendDailyReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *daemon.DailyReminder
		if args[0] != nil {
			arg0 = args[0].(*daemon.DailyReminder)
		}
		var arg1 *daemon.Output
		if args[1] != nil {
			arg1 = args[1].(*daemon.Output)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SendDailyReminder_Call) Return(err error) *MockService_SendDailyReminder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SendDailyReminder_Call) RunAndReturn(run func(dailyReminder *daemon.DailyReminder, output *daemon.Output) error) *MockService_SendDailyReminder_Call {
	_c.Call.Return(run)
	return _c
}

// SendReminder provides a mock function for the type MockService
func (_mock *MockService) SendReminder(event *daemon.Event, output *daemon.Output) error {
	ret := _mock.Called(event, output)

	if len(ret) == 0 {
		panic("no return value specified for SendReminder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*daemon.Event, *daemon.Output) error); ok {
		r0 = returnFunc(event, output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SendReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReminder'
type MockService_SendReminder_Call struct {
	*mock.Call
}

// SendReminder is a helper method to define mock.On call
//   - event *daemon.Event
//   - output *daemon.Output
func (_e *MockService_Expecter) SendReminder(event interface{}, output interface{}) *MockService_SendReminder_Call {
	return &MockService_SendReminder_Call{Call: _e.mock.On("SendReminder", event, output)}
}

func (_c *MockService_SendReminder_Call) Run(run func(event *daemon.Event, output *daemon.Output)) *MockService_SendReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *daemon.Event
		if args[0] != nil {
			arg0 = args[0].(*daemon.Event)
		}
		var arg1 *daemon.Output
		if args[1] != nil {
			arg1 = args[1].(*daemon.Output)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SendReminder_Call) Return(err error) *MockService_SendReminder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SendReminder_Call) RunAndReturn(run func(event *daemon.Event, output *daemon.Output) error) *MockService_SendReminder_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockService
func (_mock *MockService) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockService_Expecter) Start() *MockService_Start_Call {
	return &MockService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockService_Start_Call) Run(run func()) *MockService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Start_Call) Return(err error) *MockService_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Start_Call) RunAndReturn(run func() error) *MockService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockService
func (_mock *MockService) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockService_Expecter) Stop() *MockService_Stop_Call {
	return &MockService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockService_Stop_Call) Run(run func()) *MockService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Stop_Call) Return(err error) *MockService_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Stop_Call) RunAndReturn(run func() error) *MockService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// ToLocalTime provides a mock function for the type MockService
func (_mock *MockService) ToLocalTime(time1 time.Time, output *daemon.Output) time.Time {
	ret := _mock.Called(time1, output)

	if len(ret) == 0 {
		panic("no return value specified for ToLocalTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(time.Time, *daemon.Output) time.Time); ok {
		r0 = returnFunc(time1, output)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockService_ToLocalTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToLocalTime'
type MockService_ToLocalTime_Call struct {
	*mock.Call
}

// ToLocalTime is a helper method to define mock.On call
//   - time1 time.Time
//   - output *daemon.Output
func (_e *MockService_Expecter) ToLocalTime(time1 interface{}, output interface{}) *MockService_ToLocalTime_Call {
	return &MockService_ToLocalTime_Call{Call: _e.mock.On("ToLocalTime", time1, output)}
}

func (_c *MockService_ToLocalTime_Call) Run(run func(time1 time.Time, output *daemon.Output)) *MockService_ToLocalTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 *daemon.Output
		if args[1] != nil {
			arg1 = args[1].(*daemon.Output)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ToLocalTime_Call) Return(time11 time.Time) *MockService_ToLocalTime_Call {
	_c.Call.Return(time11)
	return _c
}

func (_c *MockService_ToLocalTime_Call) RunAndReturn(run func(time1 time.Time, output *daemon.Output) time.Time) *MockService_ToLocalTime_Call {
	_c.Call.Return(run)
	return _c
}
