// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mautrixcl

import (
	mock "github.com/stretchr/testify/mock"
	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/id"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// JoinedMembers provides a mock function for the type MockClient
func (_mock *MockClient) JoinedMembers(roomID id.RoomID) (*mautrix.RespJoinedMembers, error) {
	ret := _mock.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for JoinedMembers")
	}

	var r0 *mautrix.RespJoinedMembers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(id.RoomID) (*mautrix.RespJoinedMembers, error)); ok {
		return returnFunc(roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(id.RoomID) *mautrix.RespJoinedMembers); ok {
		r0 = returnFunc(roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mautrix.RespJoinedMembers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(id.RoomID) error); ok {
		r1 = returnFunc(roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_JoinedMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinedMembers'
type MockClient_JoinedMembers_Call struct {
	*mock.Call
}

// JoinedMembers is a helper method to define mock.On call
//   - roomID id.RoomID
func (_e *MockClient_Expecter) JoinedMembers(roomID interface{}) *MockClient_JoinedMembers_Call {
	return &MockClient_JoinedMembers_Call{Call: _e.mock.On("JoinedMembers", roomID)}
}

func (_c *MockClient_JoinedMembers_Call) Run(run func(roomID id.RoomID)) *MockClient_JoinedMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 id.RoomID
		if args[0] != nil {
			arg0 = args[0].(id.RoomID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_JoinedMembers_Call) Return(resp *mautrix.RespJoinedMembers, err error) *MockClient_JoinedMembers_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *MockClient_JoinedMembers_Call) RunAndReturn(run func(roomID id.RoomID) (*mautrix.RespJoinedMembers, error)) *MockClient_JoinedMembers_Call {
	_c.Call.Return(run)
	return _c
}
