// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package daemon

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOutputService creates a new instance of MockOutputService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutputService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutputService {
	mock := &MockOutputService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutputService is an autogenerated mock type for the OutputService type
type MockOutputService struct {
	mock.Mock
}

type MockOutputService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutputService) EXPECT() *MockOutputService_Expecter {
	return &MockOutputService_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type MockOutputService
func (_mock *MockOutputService) Cleanup() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutputService_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockOutputService_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockOutputService_Expecter) Cleanup() *MockOutputService_Cleanup_Call {
	return &MockOutputService_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockOutputService_Cleanup_Call) Run(run func()) *MockOutputService_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOutputService_Cleanup_Call) Return(err error) *MockOutputService_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutputService_Cleanup_Call) RunAndReturn(run func() error) *MockOutputService_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// SendDailyReminder provides a mock function for the type MockOutputService
func (_mock *MockOutputService) SendDailyReminder(dailyReminder *DailyReminder, output *Output) error {
	ret := _mock.Called(dailyReminder, output)

	if len(ret) == 0 {
		panic("no return value specified for SendDailyReminder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*DailyReminder, *Output) error); ok {
		r0 = returnFunc(dailyReminder, output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutputService_SendDailyReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDailyReminder'
type MockOutputService_SendDailyReminder_Call struct {
	*mock.Call
}

// SendDailyReminder is a helper method to define mock.On call
//   - dailyReminder *DailyReminder
//   - output *Output
func (_e *MockOutputService_Expecter) SendDailyReminder(dailyReminder interface{}, output interface{}) *MockOutputService_SendDailyReminder_Call {
	return &MockOutputService_SendDailyReminder_Call{Call: _e.mock.On("SendDailyReminder", dailyReminder, output)}
}

func (_c *MockOutputService_SendDailyReminder_Call) Run(run func(dailyReminder *DailyReminder, output *Output)) *MockOutputService_SendDailyReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *DailyReminder
		if args[0] != nil {
			arg0 = args[0].(*DailyReminder)
		}
		var arg1 *Output
		if args[1] != nil {
			arg1 = args[1].(*Output)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutputService_SendDailyReminder_Call) Return(err error) *MockOutputService_SendDailyReminder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutputService_SendDailyReminder_Call) RunAndReturn(run func(dailyReminder *DailyReminder, output *Output) error) *MockOutputService_SendDailyReminder_Call {
	_c.Call.Return(run)
	return _c
}

// SendReminder provides a mock function for the type MockOutputService
func (_mock *MockOutputService) SendReminder(event *Event, output *Output) error {
	ret := _mock.Called(event, output)

	if len(ret) == 0 {
		panic("no return value specified for SendReminder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Event, *Output) error); ok {
		r0 = returnFunc(event, output)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutputService_SendReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReminder'
type MockOutputService_SendReminder_Call struct {
	*mock.Call
}

// SendReminder is a helper method to define mock.On call
//   - event *Event
//   - output *Output
func (_e *MockOutputService_Expecter) SendReminder(event interface{}, output interface{}) *MockOutputService_SendReminder_Call {
	return &MockOutputService_SendReminder_Call{Call: _e.mock.On("SendReminder", event, output)}
}

func (_c *MockOutputService_SendReminder_Call) Run(run func(event *Event, output *Output)) *MockOutputService_SendReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Event
		if args[0] != nil {
			arg0 = args[0].(*Event)
		}
		var arg1 *Output
		if args[1] != nil {
			arg1 = args[1].(*Output)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutputService_SendReminder_Call) Return(err error) *MockOutputService_SendReminder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutputService_SendReminder_Call) RunAndReturn(run func(event *Event, output *Output) error) *MockOutputService_SendReminder_Call {
	_c.Call.Return(run)
	return _c
}

// ToLocalTime provides a mock function for the type MockOutputService
func (_mock *MockOutputService) ToLocalTime(time1 time.Time, output *Output) time.Time {
	ret := _mock.Called(time1, output)

	if len(ret) == 0 {
		panic("no return value specified for ToLocalTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(time.Time, *Output) time.Time); ok {
		r0 = returnFunc(time1, output)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockOutputService_ToLocalTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToLocalTime'
type MockOutputService_ToLocalTime_Call struct {
	*mock.Call
}

// ToLocalTime is a helper method to define mock.On call
//   - time1 time.Time
//   - output *Output
func (_e *MockOutputService_Expecter) ToLocalTime(time1 interface{}, output interface{}) *MockOutputService_ToLocalTime_Call {
	return &MockOutputService_ToLocalTime_Call{Call: _e.mock.On("ToLocalTime", time1, output)}
}

func (_c *MockOutputService_ToLocalTime_Call) Run(run func(time1 time.Time, output *Output)) *MockOutputService_ToLocalTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 *Output
		if args[1] != nil {
			arg1 = args[1].(*Output)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutputService_ToLocalTime_Call) Return(time11 time.Time) *MockOutputService_ToLocalTime_Call {
	_c.Call.Return(time11)
	return _c
}

func (_c *MockOutputService_ToLocalTime_Call) RunAndReturn(run func(time1 time.Time, output *Output) time.Time) *MockOutputService_ToLocalTime_Call {
	_c.Call.Return(run)
	return _c
}
