name: Main
on:
  push:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "index.html"

permissions:
  contents: read
  checks: write
  pages: write
  id-token: write

jobs:
  golang_quality:
    uses: CubicrootXYZ/Workflows/.github/workflows/golang_quality.yaml@v0.0.12

  golang_test:
    uses: CubicrootXYZ/Workflows/.github/workflows/golang_test.yaml@v0.0.12
    needs: [build_openapi_spec] # Validates agains OpenAPI spec
    with:
      services: '{"database": {"image": "mysql:9.0", "ports": ["3306:3306"], "env": {"MYSQL_ROOT_PASSWORD": "mypass", "MYSQL_DATABASE": "remindme"}}}'
      env: '{"TEST_DB_HOST": "database"}'

  build_openapi_spec:
    uses: CubicrootXYZ/Workflows/.github/workflows/openapi2_golang_build.yaml@v0.0.12
    with:
      entrypoint: cmd/remindme/main.go

  render_openapi_spec:
    needs: [build_openapi_spec]
    uses: CubicrootXYZ/Workflows/.github/workflows/openapi2_render.yaml@v0.0.12
    with:
      spec_artifact_name: openapi-spec
      spec_artifact_path: docs/
      spec_filename: swagger.yaml

  deploy_openapi_spec:
    needs: [render_openapi_spec]
    uses: CubicrootXYZ/Workflows/.github/workflows/pages.yaml@v0.0.12
    with:
      artifact_name: rendered-api-docu
      artifact_path: index.html

  build_image:
    needs: [golang_test, golang_quality, render_openapi_spec]
    uses: CubicrootXYZ/Workflows/.github/workflows/build_image.yaml@v0.0.12
    with:
      docker_build_args: "--no-cache"
      docker_file_path: "./"
      image_name: "cubicrootxyz/remindme"
      static_tag: "beta"
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  scan_image:
    uses: anchore/scan-action@v3
    with:
      image: "cubicrootxyz/remindme:${{ github.sha }}"
