name: Main
on: [push]
jobs: 
  # Checks the code
  test_analyze_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Install dependencies
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run tests
        run: go test ./...
      - name: Analyze Code with go vet
        run: go vet ./...
      - name: Run staticcheck
        run: staticcheck ./...
      - name: Build the app
        run: go build -o ./app ./cmd/remindme
  # Builds the image and publishes it on docker hub - only for pushes in main
  build_and_push_docker:
    needs: test_analyze_and_build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build container
        run: docker build -t cubicrootxyz/remindme .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push cubicrootxyz/remindme:latest
      
