name: Main
on:
  push:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "index.html"

permissions:
  # Required by golangci job to write annotations to the merge request.
  contents: read
  checks: write

jobs:
  golang_quality:
    uses: CubicrootXYZ/Workflows/.github/workflows/golang_quality.yaml@v0.0.8

  golang_test:
    uses: CubicrootXYZ/Workflows/.github/workflows/golang_test.yaml@v0.0.8
    needs: [build_openapi_spec] # Validates agains OpenAPI spec
    with:
      services: '{"database": {"image": "mysql:9.0", "ports": ["3306:3306"], "env": {"MYSQL_ROOT_PASSWORD": "mypass", "MYSQL_DATABASE": "remindme"}}}'
      env: '{"TEST_DB_HOST": "database"}'

  build_openapi_spec:
    uses: CubicrootXYZ/Workflows/.github/workflows/openapi2_golang_build.yaml@v0.0.10
    with:
      entrypoint: cmd/remindme/main.go

  render_openapi_spec:
    needs: 
      - build_openapi_spec
    uses: CubicrootXYZ/Workflows/.github/workflows/openapi2_render.yaml@v0.0.10
    with:
      spec_artifact_name: openapi-spec
      spec_artifact_path: docs/
      spec_filename: swagger.yaml

  deploy_openapi_spec:
    if: "${{ github.ref == 'refs/heads/main' }}"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: 
      - render_openapi_spec
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: rendered-api-docu
        uses: actions/deploy-pages@v4

  build_and_push_image:
    needs: [golang_test, golang_quality, render_openapi_spec]
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build container
        run: docker build --build-arg VERSION=${{ github.sha }} -t cubicrootxyz/remindme:beta .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push development image
        if: "${{ github.ref != 'refs/heads/main' }}"
        run: |
          docker tag cubicrootxyz/remindme:beta cubicrootxyz/remindme:${{ github.sha }}
          docker push cubicrootxyz/remindme:${{ github.sha }}
      - name: Push beta image
        if: "${{ github.ref == 'refs/heads/main' }}"
        run: docker push cubicrootxyz/remindme:beta
