name: Main
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - 'index.html'
jobs: 
  # Checks the code
  test_analyze_and_build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/v')"
    container: 
      image: cubicrootxyz/matrix-go:latest
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run tests
        run: go test ./...
      - name: Analyze Code with go vet
        run: go vet ./...
      - name: Run staticcheck
        run: staticcheck ./...
      - name: Build the app
        run: go build -o ./app ./cmd/remindme
      - name: Build the api documentation
        run: swag init --parseDependency=true -d . -g cmd/remindme/main.go
      - name: Convert to OpenApi 3
        run: openapi-code-sample-generator convert --file docs/swagger.yaml --output-file docs/swagger3.yaml
      - name: Add code samples to api documentation
        run: openapi-code-sample-generator generate --input-file docs/swagger3.yaml --output-file docs/out.yaml
      - name: Build static html
        run: npx redoc-cli bundle docs/out.yaml --output index.html
      - name: Commit static html back
        uses: stefanzweifel/git-auto-commit-action@v4

  # Builds the image and publishes it on docker hub - only for pushes in main
  build_and_push_docker:
    needs: test_analyze_and_build
    runs-on: ubuntu-latest
    if: "${{ github.ref == 'refs/heads/main' }}"
    container: 
      image: cubicrootxyz/matrix-go:latest
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'  
      - name: Build container
        run: docker build -t cubicrootxyz/remindme:beta .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push cubicrootxyz/remindme:beta
      
