name: Main
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - 'index.html'
jobs: 
  # Checks the code
  test_analyze_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Install code sample generator
        run: go install github.com/CubicrootXYZ/openapi-code-sample-generator@latest
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Install redoc
        run: sudo apt install npm && sudo npm install redoc 
      - name: Run tests
        run: go test ./...
      - name: Analyze Code with go vet
        run: go vet ./...
      - name: Run staticcheck
        run: staticcheck ./...
      - name: Build the app
        run: go build -o ./app ./cmd/remindme
      - name: Build the api documentation
        run: swag init --parseDependency=true -d . -g cmd/remindme/main.go
      - name: Add code samples to api documentation
        run: openapi-code-sample-generator generate --input-file swagger.yaml --output-file out.yaml
      - name: Build static html
        run: npx redoc-cli bundle docs/out.yaml --output index.html
      - name: Commit static html back
        uses: stefanzweifel/git-auto-commit-action@v4

  # Builds the image and publishes it on docker hub - only for pushes in main
  build_and_push_docker:
    needs: test_analyze_and_build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build container
        run: docker build -t cubicrootxyz/remindme:beta .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push cubicrootxyz/remindme:beta
      
