name: Release
on:
  release:
    types: [published]

jobs:
  # Builds the image and publishes it on docker hub
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build container
        run: docker build -t cubicrootxyz/remindme:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image (latest)
        run: docker push cubicrootxyz/remindme:latest
      - name: Tag image with version
        run: docker tag cubicrootxyz/remindme:latest cubicrootxyz/remindme:{{ github.event.release.tag_name }}
      - name: Push image (version)
        run: docker push cubicrootxyz/remindme:{{ github.event.release.tag_name }}